// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: page/v1/app_cms.proto

package page

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BrandConfig defines branding assets.
type BrandConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       string                 `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName     string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	FaviconUrl    string                 `protobuf:"bytes,4,opt,name=favicon_url,json=faviconUrl,proto3" json:"favicon_url,omitempty"`
	SplashUrl     string                 `protobuf:"bytes,5,opt,name=splash_url,json=splashUrl,proto3" json:"splash_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandConfig) Reset() {
	*x = BrandConfig{}
	mi := &file_page_v1_app_cms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandConfig) ProtoMessage() {}

func (x *BrandConfig) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandConfig.ProtoReflect.Descriptor instead.
func (*BrandConfig) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{0}
}

func (x *BrandConfig) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *BrandConfig) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *BrandConfig) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *BrandConfig) GetFaviconUrl() string {
	if x != nil {
		return x.FaviconUrl
	}
	return ""
}

func (x *BrandConfig) GetSplashUrl() string {
	if x != nil {
		return x.SplashUrl
	}
	return ""
}

// ThemeConfig defines brand styling tokens and global CSS.
type ThemeConfig struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	PrimaryColor    string                  `protobuf:"bytes,1,opt,name=primary_color,json=primaryColor,proto3" json:"primary_color,omitempty"`
	AccentColor     string                  `protobuf:"bytes,2,opt,name=accent_color,json=accentColor,proto3" json:"accent_color,omitempty"`
	BackgroundColor string                  `protobuf:"bytes,3,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	SurfaceColor    string                  `protobuf:"bytes,4,opt,name=surface_color,json=surfaceColor,proto3" json:"surface_color,omitempty"`
	TextColor       string                  `protobuf:"bytes,5,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	TextMutedColor  string                  `protobuf:"bytes,6,opt,name=text_muted_color,json=textMutedColor,proto3" json:"text_muted_color,omitempty"`
	BorderColor     string                  `protobuf:"bytes,7,opt,name=border_color,json=borderColor,proto3" json:"border_color,omitempty"`
	FontHeading     string                  `protobuf:"bytes,8,opt,name=font_heading,json=fontHeading,proto3" json:"font_heading,omitempty"`
	FontBody        string                  `protobuf:"bytes,9,opt,name=font_body,json=fontBody,proto3" json:"font_body,omitempty"`
	Radius          string                  `protobuf:"bytes,10,opt,name=radius,proto3" json:"radius,omitempty"`
	CustomCss       string                  `protobuf:"bytes,11,opt,name=custom_css,json=customCss,proto3" json:"custom_css,omitempty"`
	TrayOverrides   map[string]*TrayStyling `protobuf:"bytes,12,rep,name=tray_overrides,json=trayOverrides,proto3" json:"tray_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // specific styling overrides per tray type
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThemeConfig) Reset() {
	*x = ThemeConfig{}
	mi := &file_page_v1_app_cms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeConfig) ProtoMessage() {}

func (x *ThemeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeConfig.ProtoReflect.Descriptor instead.
func (*ThemeConfig) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{1}
}

func (x *ThemeConfig) GetPrimaryColor() string {
	if x != nil {
		return x.PrimaryColor
	}
	return ""
}

func (x *ThemeConfig) GetAccentColor() string {
	if x != nil {
		return x.AccentColor
	}
	return ""
}

func (x *ThemeConfig) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *ThemeConfig) GetSurfaceColor() string {
	if x != nil {
		return x.SurfaceColor
	}
	return ""
}

func (x *ThemeConfig) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *ThemeConfig) GetTextMutedColor() string {
	if x != nil {
		return x.TextMutedColor
	}
	return ""
}

func (x *ThemeConfig) GetBorderColor() string {
	if x != nil {
		return x.BorderColor
	}
	return ""
}

func (x *ThemeConfig) GetFontHeading() string {
	if x != nil {
		return x.FontHeading
	}
	return ""
}

func (x *ThemeConfig) GetFontBody() string {
	if x != nil {
		return x.FontBody
	}
	return ""
}

func (x *ThemeConfig) GetRadius() string {
	if x != nil {
		return x.Radius
	}
	return ""
}

func (x *ThemeConfig) GetCustomCss() string {
	if x != nil {
		return x.CustomCss
	}
	return ""
}

func (x *ThemeConfig) GetTrayOverrides() map[string]*TrayStyling {
	if x != nil {
		return x.TrayOverrides
	}
	return nil
}

// NavItem represents a header or footer navigation link.
type NavItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	External      bool                   `protobuf:"varint,5,opt,name=external,proto3" json:"external,omitempty"`
	Order         int32                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavItem) Reset() {
	*x = NavItem{}
	mi := &file_page_v1_app_cms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavItem) ProtoMessage() {}

func (x *NavItem) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavItem.ProtoReflect.Descriptor instead.
func (*NavItem) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{2}
}

func (x *NavItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NavItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NavItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NavItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *NavItem) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *NavItem) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// NavigationConfig holds global navigation definitions.
type NavigationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderLinks   []*NavItem             `protobuf:"bytes,1,rep,name=header_links,json=headerLinks,proto3" json:"header_links,omitempty"`
	FooterLinks   []*NavItem             `protobuf:"bytes,2,rep,name=footer_links,json=footerLinks,proto3" json:"footer_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationConfig) Reset() {
	*x = NavigationConfig{}
	mi := &file_page_v1_app_cms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationConfig) ProtoMessage() {}

func (x *NavigationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationConfig.ProtoReflect.Descriptor instead.
func (*NavigationConfig) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{3}
}

func (x *NavigationConfig) GetHeaderLinks() []*NavItem {
	if x != nil {
		return x.HeaderLinks
	}
	return nil
}

func (x *NavigationConfig) GetFooterLinks() []*NavItem {
	if x != nil {
		return x.FooterLinks
	}
	return nil
}

// AppCMS holds all global application settings, brand styling, feature toggles, and dynamic labels for a tenant site.
type AppCMS struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Site           string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Brand          *BrandConfig           `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Theme          *ThemeConfig           `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	FeatureToggles map[string]bool        `protobuf:"bytes,4,rep,name=feature_toggles,json=featureToggles,proto3" json:"feature_toggles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Labels         map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Navigation     *NavigationConfig      `protobuf:"bytes,6,opt,name=navigation,proto3" json:"navigation,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppCMS) Reset() {
	*x = AppCMS{}
	mi := &file_page_v1_app_cms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCMS) ProtoMessage() {}

func (x *AppCMS) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCMS.ProtoReflect.Descriptor instead.
func (*AppCMS) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{4}
}

func (x *AppCMS) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *AppCMS) GetBrand() *BrandConfig {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *AppCMS) GetTheme() *ThemeConfig {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *AppCMS) GetFeatureToggles() map[string]bool {
	if x != nil {
		return x.FeatureToggles
	}
	return nil
}

func (x *AppCMS) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AppCMS) GetNavigation() *NavigationConfig {
	if x != nil {
		return x.Navigation
	}
	return nil
}

func (x *AppCMS) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AppCMS Requests
type GetAppCMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppCMSRequest) Reset() {
	*x = GetAppCMSRequest{}
	mi := &file_page_v1_app_cms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppCMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppCMSRequest) ProtoMessage() {}

func (x *GetAppCMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppCMSRequest.ProtoReflect.Descriptor instead.
func (*GetAppCMSRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppCMSRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type UpdateAppCMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	AppCms        *AppCMS                `protobuf:"bytes,2,opt,name=app_cms,json=appCms,proto3" json:"app_cms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppCMSRequest) Reset() {
	*x = UpdateAppCMSRequest{}
	mi := &file_page_v1_app_cms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppCMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppCMSRequest) ProtoMessage() {}

func (x *UpdateAppCMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_app_cms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppCMSRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppCMSRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_app_cms_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAppCMSRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *UpdateAppCMSRequest) GetAppCms() *AppCMS {
	if x != nil {
		return x.AppCms
	}
	return nil
}

var File_page_v1_app_cms_proto protoreflect.FileDescriptor

const file_page_v1_app_cms_proto_rawDesc = "" +
	"\n" +
	"\x15page/v1/app_cms.proto\x12\apage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12page/v1/tray.proto\"\xa2\x01\n" +
	"\vBrandConfig\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\tR\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12\x1f\n" +
	"\vfavicon_url\x18\x04 \x01(\tR\n" +
	"faviconUrl\x12\x1d\n" +
	"\n" +
	"splash_url\x18\x05 \x01(\tR\tsplashUrl\"\xb0\x04\n" +
	"\vThemeConfig\x12#\n" +
	"\rprimary_color\x18\x01 \x01(\tR\fprimaryColor\x12!\n" +
	"\faccent_color\x18\x02 \x01(\tR\vaccentColor\x12)\n" +
	"\x10background_color\x18\x03 \x01(\tR\x0fbackgroundColor\x12#\n" +
	"\rsurface_color\x18\x04 \x01(\tR\fsurfaceColor\x12\x1d\n" +
	"\n" +
	"text_color\x18\x05 \x01(\tR\ttextColor\x12(\n" +
	"\x10text_muted_color\x18\x06 \x01(\tR\x0etextMutedColor\x12!\n" +
	"\fborder_color\x18\a \x01(\tR\vborderColor\x12!\n" +
	"\ffont_heading\x18\b \x01(\tR\vfontHeading\x12\x1b\n" +
	"\tfont_body\x18\t \x01(\tR\bfontBody\x12\x16\n" +
	"\x06radius\x18\n" +
	" \x01(\tR\x06radius\x12\x1d\n" +
	"\n" +
	"custom_css\x18\v \x01(\tR\tcustomCss\x12N\n" +
	"\x0etray_overrides\x18\f \x03(\v2'.page.v1.ThemeConfig.TrayOverridesEntryR\rtrayOverrides\x1aV\n" +
	"\x12TrayOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.page.v1.TrayStylingR\x05value:\x028\x01\"\x89\x01\n" +
	"\aNavItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1a\n" +
	"\bexternal\x18\x05 \x01(\bR\bexternal\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\"|\n" +
	"\x10NavigationConfig\x123\n" +
	"\fheader_links\x18\x01 \x03(\v2\x10.page.v1.NavItemR\vheaderLinks\x123\n" +
	"\ffooter_links\x18\x02 \x03(\v2\x10.page.v1.NavItemR\vfooterLinks\"\xeb\x03\n" +
	"\x06AppCMS\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12*\n" +
	"\x05brand\x18\x02 \x01(\v2\x14.page.v1.BrandConfigR\x05brand\x12*\n" +
	"\x05theme\x18\x03 \x01(\v2\x14.page.v1.ThemeConfigR\x05theme\x12L\n" +
	"\x0ffeature_toggles\x18\x04 \x03(\v2#.page.v1.AppCMS.FeatureTogglesEntryR\x0efeatureToggles\x123\n" +
	"\x06labels\x18\x05 \x03(\v2\x1b.page.v1.AppCMS.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"navigation\x18\x06 \x01(\v2\x19.page.v1.NavigationConfigR\n" +
	"navigation\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aA\n" +
	"\x13FeatureTogglesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x10GetAppCMSRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\"S\n" +
	"\x13UpdateAppCMSRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12(\n" +
	"\aapp_cms\x18\x02 \x01(\v2\x0f.page.v1.AppCMSR\x06appCmsB.Z,github.com/AyuuSaxena/protos-go/page/v1;pageb\x06proto3"

var (
	file_page_v1_app_cms_proto_rawDescOnce sync.Once
	file_page_v1_app_cms_proto_rawDescData []byte
)

func file_page_v1_app_cms_proto_rawDescGZIP() []byte {
	file_page_v1_app_cms_proto_rawDescOnce.Do(func() {
		file_page_v1_app_cms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_page_v1_app_cms_proto_rawDesc), len(file_page_v1_app_cms_proto_rawDesc)))
	})
	return file_page_v1_app_cms_proto_rawDescData
}

var file_page_v1_app_cms_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_page_v1_app_cms_proto_goTypes = []any{
	(*BrandConfig)(nil),           // 0: page.v1.BrandConfig
	(*ThemeConfig)(nil),           // 1: page.v1.ThemeConfig
	(*NavItem)(nil),               // 2: page.v1.NavItem
	(*NavigationConfig)(nil),      // 3: page.v1.NavigationConfig
	(*AppCMS)(nil),                // 4: page.v1.AppCMS
	(*GetAppCMSRequest)(nil),      // 5: page.v1.GetAppCMSRequest
	(*UpdateAppCMSRequest)(nil),   // 6: page.v1.UpdateAppCMSRequest
	nil,                           // 7: page.v1.ThemeConfig.TrayOverridesEntry
	nil,                           // 8: page.v1.AppCMS.FeatureTogglesEntry
	nil,                           // 9: page.v1.AppCMS.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*TrayStyling)(nil),           // 11: page.v1.TrayStyling
}
var file_page_v1_app_cms_proto_depIdxs = []int32{
	7,  // 0: page.v1.ThemeConfig.tray_overrides:type_name -> page.v1.ThemeConfig.TrayOverridesEntry
	2,  // 1: page.v1.NavigationConfig.header_links:type_name -> page.v1.NavItem
	2,  // 2: page.v1.NavigationConfig.footer_links:type_name -> page.v1.NavItem
	0,  // 3: page.v1.AppCMS.brand:type_name -> page.v1.BrandConfig
	1,  // 4: page.v1.AppCMS.theme:type_name -> page.v1.ThemeConfig
	8,  // 5: page.v1.AppCMS.feature_toggles:type_name -> page.v1.AppCMS.FeatureTogglesEntry
	9,  // 6: page.v1.AppCMS.labels:type_name -> page.v1.AppCMS.LabelsEntry
	3,  // 7: page.v1.AppCMS.navigation:type_name -> page.v1.NavigationConfig
	10, // 8: page.v1.AppCMS.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 9: page.v1.UpdateAppCMSRequest.app_cms:type_name -> page.v1.AppCMS
	11, // 10: page.v1.ThemeConfig.TrayOverridesEntry.value:type_name -> page.v1.TrayStyling
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_page_v1_app_cms_proto_init() }
func file_page_v1_app_cms_proto_init() {
	if File_page_v1_app_cms_proto != nil {
		return
	}
	file_page_v1_tray_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_page_v1_app_cms_proto_rawDesc), len(file_page_v1_app_cms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_page_v1_app_cms_proto_goTypes,
		DependencyIndexes: file_page_v1_app_cms_proto_depIdxs,
		MessageInfos:      file_page_v1_app_cms_proto_msgTypes,
	}.Build()
	File_page_v1_app_cms_proto = out.File
	file_page_v1_app_cms_proto_goTypes = nil
	file_page_v1_app_cms_proto_depIdxs = nil
}
