// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: page/v1/page.proto

package page

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageConfig represents both live pages and reusable template blueprints.
type PageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Site          string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`                       // "home", "landing", "catalog", "detail"
	TemplateId    string                 `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // Reference to source template if instantiated
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                           // "draft", "published", "archived"
	Seo           *SEOConfig             `protobuf:"bytes,8,opt,name=seo,proto3" json:"seo,omitempty"`
	Sections      []*SectionConfig       `protobuf:"bytes,9,rep,name=sections,proto3" json:"sections,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsTemplate    bool                   `protobuf:"varint,12,opt,name=is_template,json=isTemplate,proto3" json:"is_template,omitempty"` // true = template blueprint, false = live site page
	Modules       []*ModuleConfig        `protobuf:"bytes,13,rep,name=modules,proto3" json:"modules,omitempty"`                          // Module-wise layout for web-app mapping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageConfig) Reset() {
	*x = PageConfig{}
	mi := &file_page_v1_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageConfig) ProtoMessage() {}

func (x *PageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageConfig.ProtoReflect.Descriptor instead.
func (*PageConfig) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{0}
}

func (x *PageConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PageConfig) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *PageConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PageConfig) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PageConfig) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PageConfig) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PageConfig) GetSeo() *SEOConfig {
	if x != nil {
		return x.Seo
	}
	return nil
}

func (x *PageConfig) GetSections() []*SectionConfig {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *PageConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PageConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PageConfig) GetIsTemplate() bool {
	if x != nil {
		return x.IsTemplate
	}
	return false
}

func (x *PageConfig) GetModules() []*ModuleConfig {
	if x != nil {
		return x.Modules
	}
	return nil
}

// Page Requests / Responses
type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_page_v1_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{1}
}

func (x *GetPageRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type GetPageByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageByIDRequest) Reset() {
	*x = GetPageByIDRequest{}
	mi := &file_page_v1_page_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageByIDRequest) ProtoMessage() {}

func (x *GetPageByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPageByIDRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{2}
}

func (x *GetPageByIDRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetPageByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	IsTemplate    *bool                  `protobuf:"varint,2,opt,name=is_template,json=isTemplate,proto3,oneof" json:"is_template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_page_v1_page_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{3}
}

func (x *ListPagesRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ListPagesRequest) GetIsTemplate() bool {
	if x != nil && x.IsTemplate != nil {
		return *x.IsTemplate
	}
	return false
}

type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*PageConfig          `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_page_v1_page_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{4}
}

func (x *ListPagesResponse) GetPages() []*PageConfig {
	if x != nil {
		return x.Pages
	}
	return nil
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Page          *PageConfig            `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_page_v1_page_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePageRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *CreatePageRequest) GetPage() *PageConfig {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Page          *PageConfig            `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePageRequest) Reset() {
	*x = UpdatePageRequest{}
	mi := &file_page_v1_page_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePageRequest) ProtoMessage() {}

func (x *UpdatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePageRequest.ProtoReflect.Descriptor instead.
func (*UpdatePageRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePageRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *UpdatePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePageRequest) GetPage() *PageConfig {
	if x != nil {
		return x.Page
	}
	return nil
}

type DeletePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_page_v1_page_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePageRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *DeletePageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageResponse) Reset() {
	*x = DeletePageResponse{}
	mi := &file_page_v1_page_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageResponse) ProtoMessage() {}

func (x *DeletePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_page_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageResponse.ProtoReflect.Descriptor instead.
func (*DeletePageResponse) Descriptor() ([]byte, []int) {
	return file_page_v1_page_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_page_v1_page_proto protoreflect.FileDescriptor

const file_page_v1_page_proto_rawDesc = "" +
	"\n" +
	"\x12page/v1/page.proto\x12\apage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12page/v1/tray.proto\x1a\x11page/v1/seo.proto\"\xdf\x03\n" +
	"\n" +
	"PageConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1f\n" +
	"\vtemplate_id\x18\x06 \x01(\tR\n" +
	"templateId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12$\n" +
	"\x03seo\x18\b \x01(\v2\x12.page.v1.SEOConfigR\x03seo\x122\n" +
	"\bsections\x18\t \x03(\v2\x16.page.v1.SectionConfigR\bsections\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vis_template\x18\f \x01(\bR\n" +
	"isTemplate\x12/\n" +
	"\amodules\x18\r \x03(\v2\x15.page.v1.ModuleConfigR\amodules\"$\n" +
	"\x0eGetPageRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\"8\n" +
	"\x12GetPageByIDRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\\\n" +
	"\x10ListPagesRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12$\n" +
	"\vis_template\x18\x02 \x01(\bH\x00R\n" +
	"isTemplate\x88\x01\x01B\x0e\n" +
	"\f_is_template\">\n" +
	"\x11ListPagesResponse\x12)\n" +
	"\x05pages\x18\x01 \x03(\v2\x13.page.v1.PageConfigR\x05pages\"P\n" +
	"\x11CreatePageRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.page.v1.PageConfigR\x04page\"`\n" +
	"\x11UpdatePageRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.page.v1.PageConfigR\x04page\"7\n" +
	"\x11DeletePageRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\".\n" +
	"\x12DeletePageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB.Z,github.com/AyuuSaxena/protos-go/page/v1;pageb\x06proto3"

var (
	file_page_v1_page_proto_rawDescOnce sync.Once
	file_page_v1_page_proto_rawDescData []byte
)

func file_page_v1_page_proto_rawDescGZIP() []byte {
	file_page_v1_page_proto_rawDescOnce.Do(func() {
		file_page_v1_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_page_v1_page_proto_rawDesc), len(file_page_v1_page_proto_rawDesc)))
	})
	return file_page_v1_page_proto_rawDescData
}

var file_page_v1_page_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_page_v1_page_proto_goTypes = []any{
	(*PageConfig)(nil),            // 0: page.v1.PageConfig
	(*GetPageRequest)(nil),        // 1: page.v1.GetPageRequest
	(*GetPageByIDRequest)(nil),    // 2: page.v1.GetPageByIDRequest
	(*ListPagesRequest)(nil),      // 3: page.v1.ListPagesRequest
	(*ListPagesResponse)(nil),     // 4: page.v1.ListPagesResponse
	(*CreatePageRequest)(nil),     // 5: page.v1.CreatePageRequest
	(*UpdatePageRequest)(nil),     // 6: page.v1.UpdatePageRequest
	(*DeletePageRequest)(nil),     // 7: page.v1.DeletePageRequest
	(*DeletePageResponse)(nil),    // 8: page.v1.DeletePageResponse
	(*SEOConfig)(nil),             // 9: page.v1.SEOConfig
	(*SectionConfig)(nil),         // 10: page.v1.SectionConfig
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*ModuleConfig)(nil),          // 12: page.v1.ModuleConfig
}
var file_page_v1_page_proto_depIdxs = []int32{
	9,  // 0: page.v1.PageConfig.seo:type_name -> page.v1.SEOConfig
	10, // 1: page.v1.PageConfig.sections:type_name -> page.v1.SectionConfig
	11, // 2: page.v1.PageConfig.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: page.v1.PageConfig.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: page.v1.PageConfig.modules:type_name -> page.v1.ModuleConfig
	0,  // 5: page.v1.ListPagesResponse.pages:type_name -> page.v1.PageConfig
	0,  // 6: page.v1.CreatePageRequest.page:type_name -> page.v1.PageConfig
	0,  // 7: page.v1.UpdatePageRequest.page:type_name -> page.v1.PageConfig
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_page_v1_page_proto_init() }
func file_page_v1_page_proto_init() {
	if File_page_v1_page_proto != nil {
		return
	}
	file_page_v1_tray_proto_init()
	file_page_v1_seo_proto_init()
	file_page_v1_page_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_page_v1_page_proto_rawDesc), len(file_page_v1_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_page_v1_page_proto_goTypes,
		DependencyIndexes: file_page_v1_page_proto_depIdxs,
		MessageInfos:      file_page_v1_page_proto_msgTypes,
	}.Build()
	File_page_v1_page_proto = out.File
	file_page_v1_page_proto_goTypes = nil
	file_page_v1_page_proto_depIdxs = nil
}
