// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: page/v1/seo.proto

package page

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SEOConfig defines search engine and social graph tags for pages and templates.
type SEOConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      string                 `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	OgImage       string                 `protobuf:"bytes,4,opt,name=og_image,json=ogImage,proto3" json:"og_image,omitempty"`
	Canonical     string                 `protobuf:"bytes,5,opt,name=canonical,proto3" json:"canonical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SEOConfig) Reset() {
	*x = SEOConfig{}
	mi := &file_page_v1_seo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SEOConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEOConfig) ProtoMessage() {}

func (x *SEOConfig) ProtoReflect() protoreflect.Message {
	mi := &file_page_v1_seo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEOConfig.ProtoReflect.Descriptor instead.
func (*SEOConfig) Descriptor() ([]byte, []int) {
	return file_page_v1_seo_proto_rawDescGZIP(), []int{0}
}

func (x *SEOConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SEOConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SEOConfig) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SEOConfig) GetOgImage() string {
	if x != nil {
		return x.OgImage
	}
	return ""
}

func (x *SEOConfig) GetCanonical() string {
	if x != nil {
		return x.Canonical
	}
	return ""
}

var File_page_v1_seo_proto protoreflect.FileDescriptor

const file_page_v1_seo_proto_rawDesc = "" +
	"\n" +
	"\x11page/v1/seo.proto\x12\apage.v1\"\x98\x01\n" +
	"\tSEOConfig\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x03 \x01(\tR\bkeywords\x12\x19\n" +
	"\bog_image\x18\x04 \x01(\tR\aogImage\x12\x1c\n" +
	"\tcanonical\x18\x05 \x01(\tR\tcanonicalB.Z,github.com/AyuuSaxena/protos-go/page/v1;pageb\x06proto3"

var (
	file_page_v1_seo_proto_rawDescOnce sync.Once
	file_page_v1_seo_proto_rawDescData []byte
)

func file_page_v1_seo_proto_rawDescGZIP() []byte {
	file_page_v1_seo_proto_rawDescOnce.Do(func() {
		file_page_v1_seo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_page_v1_seo_proto_rawDesc), len(file_page_v1_seo_proto_rawDesc)))
	})
	return file_page_v1_seo_proto_rawDescData
}

var file_page_v1_seo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_page_v1_seo_proto_goTypes = []any{
	(*SEOConfig)(nil), // 0: page.v1.SEOConfig
}
var file_page_v1_seo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_page_v1_seo_proto_init() }
func file_page_v1_seo_proto_init() {
	if File_page_v1_seo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_page_v1_seo_proto_rawDesc), len(file_page_v1_seo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_page_v1_seo_proto_goTypes,
		DependencyIndexes: file_page_v1_seo_proto_depIdxs,
		MessageInfos:      file_page_v1_seo_proto_msgTypes,
	}.Build()
	File_page_v1_seo_proto = out.File
	file_page_v1_seo_proto_goTypes = nil
	file_page_v1_seo_proto_depIdxs = nil
}
