// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: management/v1/playlist/playlistService.proto

package playlist

import (
	context "context"
	playlist "github.com/AyuuSaxena/protos-go/content/v1/playlist"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaylistService_CreatePlaylist_FullMethodName     = "/management.v1.playlist.PlaylistService/CreatePlaylist"
	PlaylistService_ListPlaylists_FullMethodName      = "/management.v1.playlist.PlaylistService/ListPlaylists"
	PlaylistService_GetPlaylist_FullMethodName        = "/management.v1.playlist.PlaylistService/GetPlaylist"
	PlaylistService_UpdatePlaylist_FullMethodName     = "/management.v1.playlist.PlaylistService/UpdatePlaylist"
	PlaylistService_DeletePlaylist_FullMethodName     = "/management.v1.playlist.PlaylistService/DeletePlaylist"
	PlaylistService_AddPlaylistItem_FullMethodName    = "/management.v1.playlist.PlaylistService/AddPlaylistItem"
	PlaylistService_RemovePlaylistItem_FullMethodName = "/management.v1.playlist.PlaylistService/RemovePlaylistItem"
	PlaylistService_GetFavorites_FullMethodName       = "/management.v1.playlist.PlaylistService/GetFavorites"
	PlaylistService_AddFavorite_FullMethodName        = "/management.v1.playlist.PlaylistService/AddFavorite"
	PlaylistService_RemoveFavorite_FullMethodName     = "/management.v1.playlist.PlaylistService/RemoveFavorite"
	PlaylistService_CheckFavorites_FullMethodName     = "/management.v1.playlist.PlaylistService/CheckFavorites"
)

// PlaylistServiceClient is the client API for PlaylistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaylistServiceClient interface {
	CreatePlaylist(ctx context.Context, in *playlist.CreatePlaylistRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	ListPlaylists(ctx context.Context, in *playlist.ListPlaylistsRequest, opts ...grpc.CallOption) (*playlist.ListPlaylistsResponse, error)
	GetPlaylist(ctx context.Context, in *playlist.GetPlaylistRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	UpdatePlaylist(ctx context.Context, in *playlist.UpdatePlaylistRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	DeletePlaylist(ctx context.Context, in *playlist.DeletePlaylistRequest, opts ...grpc.CallOption) (*playlist.DeletePlaylistResponse, error)
	AddPlaylistItem(ctx context.Context, in *playlist.PlaylistItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	RemovePlaylistItem(ctx context.Context, in *playlist.PlaylistItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	GetFavorites(ctx context.Context, in *playlist.FavoritesRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	AddFavorite(ctx context.Context, in *playlist.FavoriteItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	RemoveFavorite(ctx context.Context, in *playlist.FavoriteItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error)
	CheckFavorites(ctx context.Context, in *playlist.FavoriteStatusRequest, opts ...grpc.CallOption) (*playlist.FavoriteStatusResponse, error)
}

type playlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaylistServiceClient(cc grpc.ClientConnInterface) PlaylistServiceClient {
	return &playlistServiceClient{cc}
}

func (c *playlistServiceClient) CreatePlaylist(ctx context.Context, in *playlist.CreatePlaylistRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_CreatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) ListPlaylists(ctx context.Context, in *playlist.ListPlaylistsRequest, opts ...grpc.CallOption) (*playlist.ListPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.ListPlaylistsResponse)
	err := c.cc.Invoke(ctx, PlaylistService_ListPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) GetPlaylist(ctx context.Context, in *playlist.GetPlaylistRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) UpdatePlaylist(ctx context.Context, in *playlist.UpdatePlaylistRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_UpdatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) DeletePlaylist(ctx context.Context, in *playlist.DeletePlaylistRequest, opts ...grpc.CallOption) (*playlist.DeletePlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.DeletePlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_DeletePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) AddPlaylistItem(ctx context.Context, in *playlist.PlaylistItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_AddPlaylistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) RemovePlaylistItem(ctx context.Context, in *playlist.PlaylistItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_RemovePlaylistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) GetFavorites(ctx context.Context, in *playlist.FavoritesRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_GetFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) AddFavorite(ctx context.Context, in *playlist.FavoriteItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_AddFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) RemoveFavorite(ctx context.Context, in *playlist.FavoriteItemRequest, opts ...grpc.CallOption) (*playlist.PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.PlaylistResponse)
	err := c.cc.Invoke(ctx, PlaylistService_RemoveFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playlistServiceClient) CheckFavorites(ctx context.Context, in *playlist.FavoriteStatusRequest, opts ...grpc.CallOption) (*playlist.FavoriteStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(playlist.FavoriteStatusResponse)
	err := c.cc.Invoke(ctx, PlaylistService_CheckFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaylistServiceServer is the server API for PlaylistService service.
// All implementations must embed UnimplementedPlaylistServiceServer
// for forward compatibility.
type PlaylistServiceServer interface {
	CreatePlaylist(context.Context, *playlist.CreatePlaylistRequest) (*playlist.PlaylistResponse, error)
	ListPlaylists(context.Context, *playlist.ListPlaylistsRequest) (*playlist.ListPlaylistsResponse, error)
	GetPlaylist(context.Context, *playlist.GetPlaylistRequest) (*playlist.PlaylistResponse, error)
	UpdatePlaylist(context.Context, *playlist.UpdatePlaylistRequest) (*playlist.PlaylistResponse, error)
	DeletePlaylist(context.Context, *playlist.DeletePlaylistRequest) (*playlist.DeletePlaylistResponse, error)
	AddPlaylistItem(context.Context, *playlist.PlaylistItemRequest) (*playlist.PlaylistResponse, error)
	RemovePlaylistItem(context.Context, *playlist.PlaylistItemRequest) (*playlist.PlaylistResponse, error)
	GetFavorites(context.Context, *playlist.FavoritesRequest) (*playlist.PlaylistResponse, error)
	AddFavorite(context.Context, *playlist.FavoriteItemRequest) (*playlist.PlaylistResponse, error)
	RemoveFavorite(context.Context, *playlist.FavoriteItemRequest) (*playlist.PlaylistResponse, error)
	CheckFavorites(context.Context, *playlist.FavoriteStatusRequest) (*playlist.FavoriteStatusResponse, error)
	mustEmbedUnimplementedPlaylistServiceServer()
}

// UnimplementedPlaylistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaylistServiceServer struct{}

func (UnimplementedPlaylistServiceServer) CreatePlaylist(context.Context, *playlist.CreatePlaylistRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) ListPlaylists(context.Context, *playlist.ListPlaylistsRequest) (*playlist.ListPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlaylists not implemented")
}
func (UnimplementedPlaylistServiceServer) GetPlaylist(context.Context, *playlist.GetPlaylistRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) UpdatePlaylist(context.Context, *playlist.UpdatePlaylistRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) DeletePlaylist(context.Context, *playlist.DeletePlaylistRequest) (*playlist.DeletePlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlaylist not implemented")
}
func (UnimplementedPlaylistServiceServer) AddPlaylistItem(context.Context, *playlist.PlaylistItemRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPlaylistItem not implemented")
}
func (UnimplementedPlaylistServiceServer) RemovePlaylistItem(context.Context, *playlist.PlaylistItemRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePlaylistItem not implemented")
}
func (UnimplementedPlaylistServiceServer) GetFavorites(context.Context, *playlist.FavoritesRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavorites not implemented")
}
func (UnimplementedPlaylistServiceServer) AddFavorite(context.Context, *playlist.FavoriteItemRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFavorite not implemented")
}
func (UnimplementedPlaylistServiceServer) RemoveFavorite(context.Context, *playlist.FavoriteItemRequest) (*playlist.PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedPlaylistServiceServer) CheckFavorites(context.Context, *playlist.FavoriteStatusRequest) (*playlist.FavoriteStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFavorites not implemented")
}
func (UnimplementedPlaylistServiceServer) mustEmbedUnimplementedPlaylistServiceServer() {}
func (UnimplementedPlaylistServiceServer) testEmbeddedByValue()                         {}

// UnsafePlaylistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaylistServiceServer will
// result in compilation errors.
type UnsafePlaylistServiceServer interface {
	mustEmbedUnimplementedPlaylistServiceServer()
}

func RegisterPlaylistServiceServer(s grpc.ServiceRegistrar, srv PlaylistServiceServer) {
	// If the following call panics, it indicates UnimplementedPlaylistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaylistService_ServiceDesc, srv)
}

func _PlaylistService_CreatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.CreatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).CreatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_CreatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).CreatePlaylist(ctx, req.(*playlist.CreatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_ListPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.ListPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).ListPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_ListPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).ListPlaylists(ctx, req.(*playlist.ListPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_GetPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.GetPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetPlaylist(ctx, req.(*playlist.GetPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_UpdatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.UpdatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).UpdatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_UpdatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).UpdatePlaylist(ctx, req.(*playlist.UpdatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_DeletePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.DeletePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).DeletePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_DeletePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).DeletePlaylist(ctx, req.(*playlist.DeletePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_AddPlaylistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.PlaylistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).AddPlaylistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_AddPlaylistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).AddPlaylistItem(ctx, req.(*playlist.PlaylistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_RemovePlaylistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.PlaylistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).RemovePlaylistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_RemovePlaylistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).RemovePlaylistItem(ctx, req.(*playlist.PlaylistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_GetFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.FavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).GetFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_GetFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).GetFavorites(ctx, req.(*playlist.FavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.FavoriteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_AddFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).AddFavorite(ctx, req.(*playlist.FavoriteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.FavoriteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_RemoveFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).RemoveFavorite(ctx, req.(*playlist.FavoriteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaylistService_CheckFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(playlist.FavoriteStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaylistServiceServer).CheckFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaylistService_CheckFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaylistServiceServer).CheckFavorites(ctx, req.(*playlist.FavoriteStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaylistService_ServiceDesc is the grpc.ServiceDesc for PlaylistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaylistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "management.v1.playlist.PlaylistService",
	HandlerType: (*PlaylistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlaylist",
			Handler:    _PlaylistService_CreatePlaylist_Handler,
		},
		{
			MethodName: "ListPlaylists",
			Handler:    _PlaylistService_ListPlaylists_Handler,
		},
		{
			MethodName: "GetPlaylist",
			Handler:    _PlaylistService_GetPlaylist_Handler,
		},
		{
			MethodName: "UpdatePlaylist",
			Handler:    _PlaylistService_UpdatePlaylist_Handler,
		},
		{
			MethodName: "DeletePlaylist",
			Handler:    _PlaylistService_DeletePlaylist_Handler,
		},
		{
			MethodName: "AddPlaylistItem",
			Handler:    _PlaylistService_AddPlaylistItem_Handler,
		},
		{
			MethodName: "RemovePlaylistItem",
			Handler:    _PlaylistService_RemovePlaylistItem_Handler,
		},
		{
			MethodName: "GetFavorites",
			Handler:    _PlaylistService_GetFavorites_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _PlaylistService_AddFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _PlaylistService_RemoveFavorite_Handler,
		},
		{
			MethodName: "CheckFavorites",
			Handler:    _PlaylistService_CheckFavorites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/v1/playlist/playlistService.proto",
}
