// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: storage/v1/storage.proto

package storage

import (
	v1 "github.com/AyuuSaxena/protos-go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bucket represents a storage bucket entity.
type Bucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique bucket identifier
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Bucket unique name/key
	// @gotags: `json:"key,omitempty" bson:"key,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" bson:"key,omitempty"`
	// Owner user identifier
	// @gotags: `json:"userId,omitempty" bson:"userId,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"userId,omitempty" bson:"userId,omitempty"`
	// Access key for S3 compatibility
	// @gotags: `json:"accessKey,omitempty" bson:"accessKey,omitempty"`
	AccessKey string `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"accessKey,omitempty" bson:"accessKey,omitempty"`
	// Creation timestamp in RFC3339 format
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// Source storage IDs attached to this bucket
	// @gotags: `json:"sourceIds,omitempty" bson:"sourceIds,omitempty"`
	SourceIds []string `protobuf:"bytes,6,rep,name=source_ids,json=sourceIds,proto3" json:"sourceIds,omitempty" bson:"sourceIds,omitempty"`
	// Distribution strategy (e.g. round_robin, weighted)
	// @gotags: `json:"distributionStrategy,omitempty" bson:"distributionStrategy,omitempty"`
	DistributionStrategy string `protobuf:"bytes,7,opt,name=distribution_strategy,json=distributionStrategy,proto3" json:"distributionStrategy,omitempty" bson:"distributionStrategy,omitempty"`
	// Weight map for weighted distribution strategy
	// @gotags: `json:"sourceWeights,omitempty" bson:"sourceWeights,omitempty"`
	SourceWeights map[string]int32 `protobuf:"bytes,8,rep,name=source_weights,json=sourceWeights,proto3" json:"sourceWeights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" bson:"sourceWeights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Bucket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bucket) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Bucket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bucket) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Bucket) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Bucket) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *Bucket) GetDistributionStrategy() string {
	if x != nil {
		return x.DistributionStrategy
	}
	return ""
}

func (x *Bucket) GetSourceWeights() map[string]int32 {
	if x != nil {
		return x.SourceWeights
	}
	return nil
}

// File represents a stored file/object record.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB internal record identifier
	// @gotags: `json:"mongoId,omitempty" bson:"_id,omitempty"`
	MongoId string `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongoId,omitempty" bson:"_id,omitempty"`
	// Unique file identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Bucket identifier
	// @gotags: `json:"bucketId,omitempty" bson:"bucketId,omitempty"`
	BucketId string `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucketId,omitempty" bson:"bucketId,omitempty"`
	// Directory path within the bucket
	// @gotags: `json:"directory,omitempty" bson:"directory,omitempty"`
	Directory string `protobuf:"bytes,4,opt,name=directory,proto3" json:"directory,omitempty" bson:"directory,omitempty"`
	// File name
	// @gotags: `json:"name,omitempty" bson:"name,omitempty"`
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	// File size in bytes
	// @gotags: `json:"size,omitempty" bson:"size,omitempty"`
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty" bson:"size,omitempty"`
	// MIME content type
	// @gotags: `json:"contentType,omitempty" bson:"contentType,omitempty"`
	ContentType string `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"contentType,omitempty" bson:"contentType,omitempty"`
	// ETag / Checksum
	// @gotags: `json:"etag,omitempty" bson:"etag,omitempty"`
	Etag string `protobuf:"bytes,8,opt,name=etag,proto3" json:"etag,omitempty" bson:"etag,omitempty"`
	// File Extension
	// @gotags: `json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	FileExtension string `protobuf:"bytes,9,opt,name=file_extension,json=fileExtension,proto3" json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	// Custom user metadata
	// @gotags: `json:"userMetadata,omitempty" bson:"userMetadata,omitempty"`
	UserMetadata map[string]string `protobuf:"bytes,10,rep,name=user_metadata,json=userMetadata,proto3" json:"userMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"userMetadata,omitempty"`
	// Creation timestamp in RFC3339 format
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt     string `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *File) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *File) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *File) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *File) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *File) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// FileChunk represents a chunk of binary file content
// for streaming upload/download.
type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Binary payload
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Current chunk index (0-based)
	ChunkNumber int32 `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	// Total expected chunks if known
	TotalChunks   int32 `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *FileChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

// Create
type CreateBucketRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Key                  string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	SourceIds            []string               `protobuf:"bytes,2,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	RiskAcknowledged     *bool                  `protobuf:"varint,3,opt,name=risk_acknowledged,json=riskAcknowledged,proto3,oneof" json:"risk_acknowledged,omitempty"`
	DistributionStrategy *string                `protobuf:"bytes,4,opt,name=distribution_strategy,json=distributionStrategy,proto3,oneof" json:"distribution_strategy,omitempty"`
	SourceWeights        map[string]int32       `protobuf:"bytes,5,rep,name=source_weights,json=sourceWeights,proto3" json:"source_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBucketRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateBucketRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *CreateBucketRequest) GetRiskAcknowledged() bool {
	if x != nil && x.RiskAcknowledged != nil {
		return *x.RiskAcknowledged
	}
	return false
}

func (x *CreateBucketRequest) GetDistributionStrategy() string {
	if x != nil && x.DistributionStrategy != nil {
		return *x.DistributionStrategy
	}
	return ""
}

func (x *CreateBucketRequest) GetSourceWeights() map[string]int32 {
	if x != nil {
		return x.SourceWeights
	}
	return nil
}

// Get
type GetBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketRequest) Reset() {
	*x = GetBucketRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketRequest) ProtoMessage() {}

func (x *GetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketRequest.ProtoReflect.Descriptor instead.
func (*GetBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetBucketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// List
type ListBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.CommonListRequest  `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ListBucketsRequest) GetPagination() *v1.CommonListRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Delete
type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBucketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GetFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// List
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Directory     *string                `protobuf:"bytes,2,opt,name=directory,proto3,oneof" json:"directory,omitempty"`
	Query         *string                `protobuf:"bytes,3,opt,name=query,proto3,oneof" json:"query,omitempty"`
	Pagination    *v1.CommonListRequest  `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilesRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *ListFilesRequest) GetDirectory() string {
	if x != nil && x.Directory != nil {
		return *x.Directory
	}
	return ""
}

func (x *ListFilesRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *ListFilesRequest) GetPagination() *v1.CommonListRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Delete
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// Upload
type UploadFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directory     *string                `protobuf:"bytes,3,opt,name=directory,proto3,oneof" json:"directory,omitempty"`
	ContentType   *string                `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	Size          *int64                 `protobuf:"varint,5,opt,name=size,proto3,oneof" json:"size,omitempty"`
	UserMetadata  map[string]string      `protobuf:"bytes,6,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileInfo) Reset() {
	*x = UploadFileInfo{}
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileInfo) ProtoMessage() {}

func (x *UploadFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileInfo.ProtoReflect.Descriptor instead.
func (*UploadFileInfo) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileInfo) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *UploadFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileInfo) GetDirectory() string {
	if x != nil && x.Directory != nil {
		return *x.Directory
	}
	return ""
}

func (x *UploadFileInfo) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *UploadFileInfo) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *UploadFileInfo) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileRequest_Info
	//	*UploadFileRequest_ChunkData
	Payload       isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileRequest) GetPayload() isUploadFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileRequest) GetInfo() *UploadFileInfo {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type UploadFileRequest_Info struct {
	Info *UploadFileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadFileRequest_Info) isUploadFileRequest_Payload() {}

func (*UploadFileRequest_ChunkData) isUploadFileRequest_Payload() {}

// Download
type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadFileRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *DownloadFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// Create
type CreateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        *Bucket                `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessSecret  string                 `protobuf:"bytes,2,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResponse) Reset() {
	*x = CreateBucketResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResponse) ProtoMessage() {}

func (x *CreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBucketResponse) GetBucket() *Bucket {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *CreateBucketResponse) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

// List
type ListBucketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*Bucket              `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Pagination    *v1.CommonListResponse `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{14}
}

func (x *ListBucketsResponse) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *ListBucketsResponse) GetPagination() *v1.CommonListResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Delete
type DeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketResponse) Reset() {
	*x = DeleteBucketResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResponse) ProtoMessage() {}

func (x *DeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteBucketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBucketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List
type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Pagination    *v1.CommonListResponse `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{16}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetPagination() *v1.CommonListResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Delete
type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Upload
type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{18}
}

func (x *UploadFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

// File response
type FileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique file identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// File name
	// @gotags: `json:"name,omitempty" bson:"name,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	// File Extension
	// @gotags: `json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	FileExtension string `protobuf:"bytes,3,opt,name=file_extension,json=fileExtension,proto3" json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	// File size in bytes
	// @gotags: `json:"size,omitempty" bson:"size,omitempty"`
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty" bson:"size,omitempty"`
	// MIME content type
	// @gotags: `json:"contentType,omitempty" bson:"contentType,omitempty"`
	ContentType string `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"contentType,omitempty" bson:"contentType,omitempty"`
	// ETag / Checksum
	// @gotags: `json:"etag,omitempty" bson:"etag,omitempty"`
	Etag string `protobuf:"bytes,8,opt,name=etag,proto3" json:"etag,omitempty" bson:"etag,omitempty"`
	// Custom user metadata
	// @gotags: `json:"userMetadata,omitempty" bson:"userMetadata,omitempty"`
	UserMetadata map[string]string `protobuf:"bytes,9,rep,name=user_metadata,json=userMetadata,proto3" json:"userMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"userMetadata,omitempty"`
	// Creation timestamp in RFC3339 format
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt     string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{19}
}

func (x *FileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileResponse) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *FileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileResponse) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *FileResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\n" +
	"storage.v1\x1a\x16common/v1/common.proto\"\xe5\x02\n" +
	"\x06Bucket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x06 \x03(\tR\tsourceIds\x123\n" +
	"\x15distribution_strategy\x18\a \x01(\tR\x14distributionStrategy\x12L\n" +
	"\x0esource_weights\x18\b \x03(\v2%.storage.v1.Bucket.SourceWeightsEntryR\rsourceWeights\x1a@\n" +
	"\x12SourceWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9b\x03\n" +
	"\x04File\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\x12\x1c\n" +
	"\tdirectory\x18\x04 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12\x12\n" +
	"\x04etag\x18\b \x01(\tR\x04etag\x12%\n" +
	"\x0efile_extension\x18\t \x01(\tR\rfileExtension\x12G\n" +
	"\ruser_metadata\x18\n" +
	" \x03(\v2\".storage.v1.File.UserMetadataEntryR\fuserMetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"\xff\x02\n" +
	"\x13CreateBucketRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x02 \x03(\tR\tsourceIds\x120\n" +
	"\x11risk_acknowledged\x18\x03 \x01(\bH\x00R\x10riskAcknowledged\x88\x01\x01\x128\n" +
	"\x15distribution_strategy\x18\x04 \x01(\tH\x01R\x14distributionStrategy\x88\x01\x01\x12Y\n" +
	"\x0esource_weights\x18\x05 \x03(\v22.storage.v1.CreateBucketRequest.SourceWeightsEntryR\rsourceWeights\x1a@\n" +
	"\x12SourceWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x14\n" +
	"\x12_risk_acknowledgedB\x18\n" +
	"\x16_distribution_strategy\"\"\n" +
	"\x10GetBucketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\x12ListBucketsRequest\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.CommonListRequestH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"%\n" +
	"\x13DeleteBucketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x0eGetFileRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"\xd7\x01\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12!\n" +
	"\tdirectory\x18\x02 \x01(\tH\x00R\tdirectory\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x03 \x01(\tH\x01R\x05query\x88\x01\x01\x12A\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1c.common.v1.CommonListRequestH\x02R\n" +
	"pagination\x88\x01\x01B\f\n" +
	"\n" +
	"_directoryB\b\n" +
	"\x06_queryB\r\n" +
	"\v_pagination\"I\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"\xe1\x02\n" +
	"\x0eUploadFileInfo\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tdirectory\x18\x03 \x01(\tH\x00R\tdirectory\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x04 \x01(\tH\x01R\vcontentType\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x05 \x01(\x03H\x02R\x04size\x88\x01\x01\x12Q\n" +
	"\ruser_metadata\x18\x06 \x03(\v2,.storage.v1.UploadFileInfo.UserMetadataEntryR\fuserMetadata\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_directoryB\x0f\n" +
	"\r_content_typeB\a\n" +
	"\x05_size\"q\n" +
	"\x11UploadFileRequest\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1a.storage.v1.UploadFileInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"K\n" +
	"\x13DownloadFileRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"g\n" +
	"\x14CreateBucketResponse\x12*\n" +
	"\x06bucket\x18\x01 \x01(\v2\x12.storage.v1.BucketR\x06bucket\x12#\n" +
	"\raccess_secret\x18\x02 \x01(\tR\faccessSecret\"\x96\x01\n" +
	"\x13ListBucketsResponse\x12,\n" +
	"\abuckets\x18\x01 \x03(\v2\x12.storage.v1.BucketR\abuckets\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.CommonListResponseH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"J\n" +
	"\x14DeleteBucketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x11ListFilesResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.storage.v1.FileR\x05files\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.CommonListResponseH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"H\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x12UploadFileResponse\x12$\n" +
	"\x04file\x18\x01 \x01(\v2\x10.storage.v1.FileR\x04file\"\xd5\x02\n" +
	"\fFileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0efile_extension\x18\x03 \x01(\tR\rfileExtension\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12\x12\n" +
	"\x04etag\x18\b \x01(\tR\x04etag\x12O\n" +
	"\ruser_metadata\x18\t \x03(\v2*.storage.v1.FileResponse.UserMetadataEntryR\fuserMetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B4Z2github.com/AyuuSaxena/protos-go/storage/v1;storageb\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_storage_v1_storage_proto_goTypes = []any{
	(*Bucket)(nil),                // 0: storage.v1.Bucket
	(*File)(nil),                  // 1: storage.v1.File
	(*FileChunk)(nil),             // 2: storage.v1.FileChunk
	(*CreateBucketRequest)(nil),   // 3: storage.v1.CreateBucketRequest
	(*GetBucketRequest)(nil),      // 4: storage.v1.GetBucketRequest
	(*ListBucketsRequest)(nil),    // 5: storage.v1.ListBucketsRequest
	(*DeleteBucketRequest)(nil),   // 6: storage.v1.DeleteBucketRequest
	(*GetFileRequest)(nil),        // 7: storage.v1.GetFileRequest
	(*ListFilesRequest)(nil),      // 8: storage.v1.ListFilesRequest
	(*DeleteFileRequest)(nil),     // 9: storage.v1.DeleteFileRequest
	(*UploadFileInfo)(nil),        // 10: storage.v1.UploadFileInfo
	(*UploadFileRequest)(nil),     // 11: storage.v1.UploadFileRequest
	(*DownloadFileRequest)(nil),   // 12: storage.v1.DownloadFileRequest
	(*CreateBucketResponse)(nil),  // 13: storage.v1.CreateBucketResponse
	(*ListBucketsResponse)(nil),   // 14: storage.v1.ListBucketsResponse
	(*DeleteBucketResponse)(nil),  // 15: storage.v1.DeleteBucketResponse
	(*ListFilesResponse)(nil),     // 16: storage.v1.ListFilesResponse
	(*DeleteFileResponse)(nil),    // 17: storage.v1.DeleteFileResponse
	(*UploadFileResponse)(nil),    // 18: storage.v1.UploadFileResponse
	(*FileResponse)(nil),          // 19: storage.v1.FileResponse
	nil,                           // 20: storage.v1.Bucket.SourceWeightsEntry
	nil,                           // 21: storage.v1.File.UserMetadataEntry
	nil,                           // 22: storage.v1.CreateBucketRequest.SourceWeightsEntry
	nil,                           // 23: storage.v1.UploadFileInfo.UserMetadataEntry
	nil,                           // 24: storage.v1.FileResponse.UserMetadataEntry
	(*v1.CommonListRequest)(nil),  // 25: common.v1.CommonListRequest
	(*v1.CommonListResponse)(nil), // 26: common.v1.CommonListResponse
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	20, // 0: storage.v1.Bucket.source_weights:type_name -> storage.v1.Bucket.SourceWeightsEntry
	21, // 1: storage.v1.File.user_metadata:type_name -> storage.v1.File.UserMetadataEntry
	22, // 2: storage.v1.CreateBucketRequest.source_weights:type_name -> storage.v1.CreateBucketRequest.SourceWeightsEntry
	25, // 3: storage.v1.ListBucketsRequest.pagination:type_name -> common.v1.CommonListRequest
	25, // 4: storage.v1.ListFilesRequest.pagination:type_name -> common.v1.CommonListRequest
	23, // 5: storage.v1.UploadFileInfo.user_metadata:type_name -> storage.v1.UploadFileInfo.UserMetadataEntry
	10, // 6: storage.v1.UploadFileRequest.info:type_name -> storage.v1.UploadFileInfo
	0,  // 7: storage.v1.CreateBucketResponse.bucket:type_name -> storage.v1.Bucket
	0,  // 8: storage.v1.ListBucketsResponse.buckets:type_name -> storage.v1.Bucket
	26, // 9: storage.v1.ListBucketsResponse.pagination:type_name -> common.v1.CommonListResponse
	1,  // 10: storage.v1.ListFilesResponse.files:type_name -> storage.v1.File
	26, // 11: storage.v1.ListFilesResponse.pagination:type_name -> common.v1.CommonListResponse
	1,  // 12: storage.v1.UploadFileResponse.file:type_name -> storage.v1.File
	24, // 13: storage.v1.FileResponse.user_metadata:type_name -> storage.v1.FileResponse.UserMetadataEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	file_storage_v1_storage_proto_msgTypes[3].OneofWrappers = []any{}
	file_storage_v1_storage_proto_msgTypes[5].OneofWrappers = []any{}
	file_storage_v1_storage_proto_msgTypes[8].OneofWrappers = []any{}
	file_storage_v1_storage_proto_msgTypes[10].OneofWrappers = []any{}
	file_storage_v1_storage_proto_msgTypes[11].OneofWrappers = []any{
		(*UploadFileRequest_Info)(nil),
		(*UploadFileRequest_ChunkData)(nil),
	}
	file_storage_v1_storage_proto_msgTypes[14].OneofWrappers = []any{}
	file_storage_v1_storage_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
