// Code generated by MockGen. DO NOT EDIT.
// Source: protos-go/content/v1/rom/romService_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=protos-go/content/v1/rom/romService_grpc.pb.go -destination=protos-go/mocks/content/v1/rom/romService_mock.go -package=rom_mock
//

// Package rom_mock is a generated GoMock package.
package rom_mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/AyuuSaxena/protos-go/common/v1"
	rom "github.com/AyuuSaxena/protos-go/content/v1/rom"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRomServiceClient is a mock of RomServiceClient interface.
type MockRomServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockRomServiceClientMockRecorder
	isgomock struct{}
}

// MockRomServiceClientMockRecorder is the mock recorder for MockRomServiceClient.
type MockRomServiceClientMockRecorder struct {
	mock *MockRomServiceClient
}

// NewMockRomServiceClient creates a new mock instance.
func NewMockRomServiceClient(ctrl *gomock.Controller) *MockRomServiceClient {
	mock := &MockRomServiceClient{ctrl: ctrl}
	mock.recorder = &MockRomServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRomServiceClient) EXPECT() *MockRomServiceClientMockRecorder {
	return m.recorder
}

// ListConsoles mocks base method.
func (m *MockRomServiceClient) ListConsoles(ctx context.Context, in *rom.ListConsolesRequest, opts ...grpc.CallOption) (*rom.ListConsolesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListConsoles", varargs...)
	ret0, _ := ret[0].(*rom.ListConsolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsoles indicates an expected call of ListConsoles.
func (mr *MockRomServiceClientMockRecorder) ListConsoles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsoles", reflect.TypeOf((*MockRomServiceClient)(nil).ListConsoles), varargs...)
}

// RomDelete mocks base method.
func (m *MockRomServiceClient) RomDelete(ctx context.Context, in *rom.RomDeleteRequest, opts ...grpc.CallOption) (*rom.RomDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomDelete", varargs...)
	ret0, _ := ret[0].(*rom.RomDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomDelete indicates an expected call of RomDelete.
func (mr *MockRomServiceClientMockRecorder) RomDelete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomDelete", reflect.TypeOf((*MockRomServiceClient)(nil).RomDelete), varargs...)
}

// RomDownload mocks base method.
func (m *MockRomServiceClient) RomDownload(ctx context.Context, in *rom.RomDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.FileChunk], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomDownload", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[v1.FileChunk])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomDownload indicates an expected call of RomDownload.
func (mr *MockRomServiceClientMockRecorder) RomDownload(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomDownload", reflect.TypeOf((*MockRomServiceClient)(nil).RomDownload), varargs...)
}

// RomGet mocks base method.
func (m *MockRomServiceClient) RomGet(ctx context.Context, in *rom.RomGetRequest, opts ...grpc.CallOption) (*rom.RomResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomGet", varargs...)
	ret0, _ := ret[0].(*rom.RomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomGet indicates an expected call of RomGet.
func (mr *MockRomServiceClientMockRecorder) RomGet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomGet", reflect.TypeOf((*MockRomServiceClient)(nil).RomGet), varargs...)
}

// RomSearch mocks base method.
func (m *MockRomServiceClient) RomSearch(ctx context.Context, in *rom.RomSearchRequest, opts ...grpc.CallOption) (*rom.RomSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomSearch", varargs...)
	ret0, _ := ret[0].(*rom.RomSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomSearch indicates an expected call of RomSearch.
func (mr *MockRomServiceClientMockRecorder) RomSearch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomSearch", reflect.TypeOf((*MockRomServiceClient)(nil).RomSearch), varargs...)
}

// RomShare mocks base method.
func (m *MockRomServiceClient) RomShare(ctx context.Context, in *rom.RomShareRequest, opts ...grpc.CallOption) (*rom.RomShareResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomShare", varargs...)
	ret0, _ := ret[0].(*rom.RomShareResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomShare indicates an expected call of RomShare.
func (mr *MockRomServiceClientMockRecorder) RomShare(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomShare", reflect.TypeOf((*MockRomServiceClient)(nil).RomShare), varargs...)
}

// RomUpdate mocks base method.
func (m *MockRomServiceClient) RomUpdate(ctx context.Context, in *rom.RomCreateOrUpdateRequest, opts ...grpc.CallOption) (*rom.RomResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomUpdate", varargs...)
	ret0, _ := ret[0].(*rom.RomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomUpdate indicates an expected call of RomUpdate.
func (mr *MockRomServiceClientMockRecorder) RomUpdate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomUpdate", reflect.TypeOf((*MockRomServiceClient)(nil).RomUpdate), varargs...)
}

// RomUpload mocks base method.
func (m *MockRomServiceClient) RomUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[rom.RomUploadRequest, rom.RomUploadResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RomUpload", varargs...)
	ret0, _ := ret[0].(grpc.ClientStreamingClient[rom.RomUploadRequest, rom.RomUploadResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomUpload indicates an expected call of RomUpload.
func (mr *MockRomServiceClientMockRecorder) RomUpload(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomUpload", reflect.TypeOf((*MockRomServiceClient)(nil).RomUpload), varargs...)
}

// MockRomServiceServer is a mock of RomServiceServer interface.
type MockRomServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockRomServiceServerMockRecorder
	isgomock struct{}
}

// MockRomServiceServerMockRecorder is the mock recorder for MockRomServiceServer.
type MockRomServiceServerMockRecorder struct {
	mock *MockRomServiceServer
}

// NewMockRomServiceServer creates a new mock instance.
func NewMockRomServiceServer(ctrl *gomock.Controller) *MockRomServiceServer {
	mock := &MockRomServiceServer{ctrl: ctrl}
	mock.recorder = &MockRomServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRomServiceServer) EXPECT() *MockRomServiceServerMockRecorder {
	return m.recorder
}

// ListConsoles mocks base method.
func (m *MockRomServiceServer) ListConsoles(arg0 context.Context, arg1 *rom.ListConsolesRequest) (*rom.ListConsolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsoles", arg0, arg1)
	ret0, _ := ret[0].(*rom.ListConsolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsoles indicates an expected call of ListConsoles.
func (mr *MockRomServiceServerMockRecorder) ListConsoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsoles", reflect.TypeOf((*MockRomServiceServer)(nil).ListConsoles), arg0, arg1)
}

// RomDelete mocks base method.
func (m *MockRomServiceServer) RomDelete(arg0 context.Context, arg1 *rom.RomDeleteRequest) (*rom.RomDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomDelete", arg0, arg1)
	ret0, _ := ret[0].(*rom.RomDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomDelete indicates an expected call of RomDelete.
func (mr *MockRomServiceServerMockRecorder) RomDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomDelete", reflect.TypeOf((*MockRomServiceServer)(nil).RomDelete), arg0, arg1)
}

// RomDownload mocks base method.
func (m *MockRomServiceServer) RomDownload(arg0 *rom.RomDownloadRequest, arg1 grpc.ServerStreamingServer[v1.FileChunk]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomDownload", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RomDownload indicates an expected call of RomDownload.
func (mr *MockRomServiceServerMockRecorder) RomDownload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomDownload", reflect.TypeOf((*MockRomServiceServer)(nil).RomDownload), arg0, arg1)
}

// RomGet mocks base method.
func (m *MockRomServiceServer) RomGet(arg0 context.Context, arg1 *rom.RomGetRequest) (*rom.RomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomGet", arg0, arg1)
	ret0, _ := ret[0].(*rom.RomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomGet indicates an expected call of RomGet.
func (mr *MockRomServiceServerMockRecorder) RomGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomGet", reflect.TypeOf((*MockRomServiceServer)(nil).RomGet), arg0, arg1)
}

// RomSearch mocks base method.
func (m *MockRomServiceServer) RomSearch(arg0 context.Context, arg1 *rom.RomSearchRequest) (*rom.RomSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomSearch", arg0, arg1)
	ret0, _ := ret[0].(*rom.RomSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomSearch indicates an expected call of RomSearch.
func (mr *MockRomServiceServerMockRecorder) RomSearch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomSearch", reflect.TypeOf((*MockRomServiceServer)(nil).RomSearch), arg0, arg1)
}

// RomShare mocks base method.
func (m *MockRomServiceServer) RomShare(arg0 context.Context, arg1 *rom.RomShareRequest) (*rom.RomShareResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomShare", arg0, arg1)
	ret0, _ := ret[0].(*rom.RomShareResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomShare indicates an expected call of RomShare.
func (mr *MockRomServiceServerMockRecorder) RomShare(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomShare", reflect.TypeOf((*MockRomServiceServer)(nil).RomShare), arg0, arg1)
}

// RomUpdate mocks base method.
func (m *MockRomServiceServer) RomUpdate(arg0 context.Context, arg1 *rom.RomCreateOrUpdateRequest) (*rom.RomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomUpdate", arg0, arg1)
	ret0, _ := ret[0].(*rom.RomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RomUpdate indicates an expected call of RomUpdate.
func (mr *MockRomServiceServerMockRecorder) RomUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomUpdate", reflect.TypeOf((*MockRomServiceServer)(nil).RomUpdate), arg0, arg1)
}

// RomUpload mocks base method.
func (m *MockRomServiceServer) RomUpload(arg0 grpc.ClientStreamingServer[rom.RomUploadRequest, rom.RomUploadResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RomUpload", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RomUpload indicates an expected call of RomUpload.
func (mr *MockRomServiceServerMockRecorder) RomUpload(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RomUpload", reflect.TypeOf((*MockRomServiceServer)(nil).RomUpload), arg0)
}

// mustEmbedUnimplementedRomServiceServer mocks base method.
func (m *MockRomServiceServer) mustEmbedUnimplementedRomServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedRomServiceServer")
}

// mustEmbedUnimplementedRomServiceServer indicates an expected call of mustEmbedUnimplementedRomServiceServer.
func (mr *MockRomServiceServerMockRecorder) mustEmbedUnimplementedRomServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedRomServiceServer", reflect.TypeOf((*MockRomServiceServer)(nil).mustEmbedUnimplementedRomServiceServer))
}

// MockUnsafeRomServiceServer is a mock of UnsafeRomServiceServer interface.
type MockUnsafeRomServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeRomServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeRomServiceServerMockRecorder is the mock recorder for MockUnsafeRomServiceServer.
type MockUnsafeRomServiceServerMockRecorder struct {
	mock *MockUnsafeRomServiceServer
}

// NewMockUnsafeRomServiceServer creates a new mock instance.
func NewMockUnsafeRomServiceServer(ctrl *gomock.Controller) *MockUnsafeRomServiceServer {
	mock := &MockUnsafeRomServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeRomServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeRomServiceServer) EXPECT() *MockUnsafeRomServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedRomServiceServer mocks base method.
func (m *MockUnsafeRomServiceServer) mustEmbedUnimplementedRomServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedRomServiceServer")
}

// mustEmbedUnimplementedRomServiceServer indicates an expected call of mustEmbedUnimplementedRomServiceServer.
func (mr *MockUnsafeRomServiceServerMockRecorder) mustEmbedUnimplementedRomServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedRomServiceServer", reflect.TypeOf((*MockUnsafeRomServiceServer)(nil).mustEmbedUnimplementedRomServiceServer))
}
