// Code generated by MockGen. DO NOT EDIT.
// Source: protos-go/management/v1/console/consoleService_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=protos-go/management/v1/console/consoleService_grpc.pb.go -destination=protos-go/mocks/management/v1/console/consoleService_mock.go -package=console_mock
//

// Package console_mock is a generated GoMock package.
package console_mock

import (
	context "context"
	reflect "reflect"

	rom "github.com/AyuuSaxena/protos-go/content/v1/rom"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockConsoleServiceClient is a mock of ConsoleServiceClient interface.
type MockConsoleServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockConsoleServiceClientMockRecorder
	isgomock struct{}
}

// MockConsoleServiceClientMockRecorder is the mock recorder for MockConsoleServiceClient.
type MockConsoleServiceClientMockRecorder struct {
	mock *MockConsoleServiceClient
}

// NewMockConsoleServiceClient creates a new mock instance.
func NewMockConsoleServiceClient(ctrl *gomock.Controller) *MockConsoleServiceClient {
	mock := &MockConsoleServiceClient{ctrl: ctrl}
	mock.recorder = &MockConsoleServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsoleServiceClient) EXPECT() *MockConsoleServiceClientMockRecorder {
	return m.recorder
}

// ListConsoles mocks base method.
func (m *MockConsoleServiceClient) ListConsoles(ctx context.Context, in *rom.ListConsolesRequest, opts ...grpc.CallOption) (*rom.ListConsolesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListConsoles", varargs...)
	ret0, _ := ret[0].(*rom.ListConsolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsoles indicates an expected call of ListConsoles.
func (mr *MockConsoleServiceClientMockRecorder) ListConsoles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsoles", reflect.TypeOf((*MockConsoleServiceClient)(nil).ListConsoles), varargs...)
}

// MockConsoleServiceServer is a mock of ConsoleServiceServer interface.
type MockConsoleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockConsoleServiceServerMockRecorder
	isgomock struct{}
}

// MockConsoleServiceServerMockRecorder is the mock recorder for MockConsoleServiceServer.
type MockConsoleServiceServerMockRecorder struct {
	mock *MockConsoleServiceServer
}

// NewMockConsoleServiceServer creates a new mock instance.
func NewMockConsoleServiceServer(ctrl *gomock.Controller) *MockConsoleServiceServer {
	mock := &MockConsoleServiceServer{ctrl: ctrl}
	mock.recorder = &MockConsoleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsoleServiceServer) EXPECT() *MockConsoleServiceServerMockRecorder {
	return m.recorder
}

// ListConsoles mocks base method.
func (m *MockConsoleServiceServer) ListConsoles(arg0 context.Context, arg1 *rom.ListConsolesRequest) (*rom.ListConsolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsoles", arg0, arg1)
	ret0, _ := ret[0].(*rom.ListConsolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsoles indicates an expected call of ListConsoles.
func (mr *MockConsoleServiceServerMockRecorder) ListConsoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsoles", reflect.TypeOf((*MockConsoleServiceServer)(nil).ListConsoles), arg0, arg1)
}

// mustEmbedUnimplementedConsoleServiceServer mocks base method.
func (m *MockConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedConsoleServiceServer")
}

// mustEmbedUnimplementedConsoleServiceServer indicates an expected call of mustEmbedUnimplementedConsoleServiceServer.
func (mr *MockConsoleServiceServerMockRecorder) mustEmbedUnimplementedConsoleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedConsoleServiceServer", reflect.TypeOf((*MockConsoleServiceServer)(nil).mustEmbedUnimplementedConsoleServiceServer))
}

// MockUnsafeConsoleServiceServer is a mock of UnsafeConsoleServiceServer interface.
type MockUnsafeConsoleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeConsoleServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeConsoleServiceServerMockRecorder is the mock recorder for MockUnsafeConsoleServiceServer.
type MockUnsafeConsoleServiceServerMockRecorder struct {
	mock *MockUnsafeConsoleServiceServer
}

// NewMockUnsafeConsoleServiceServer creates a new mock instance.
func NewMockUnsafeConsoleServiceServer(ctrl *gomock.Controller) *MockUnsafeConsoleServiceServer {
	mock := &MockUnsafeConsoleServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeConsoleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeConsoleServiceServer) EXPECT() *MockUnsafeConsoleServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedConsoleServiceServer mocks base method.
func (m *MockUnsafeConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedConsoleServiceServer")
}

// mustEmbedUnimplementedConsoleServiceServer indicates an expected call of mustEmbedUnimplementedConsoleServiceServer.
func (mr *MockUnsafeConsoleServiceServerMockRecorder) mustEmbedUnimplementedConsoleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedConsoleServiceServer", reflect.TypeOf((*MockUnsafeConsoleServiceServer)(nil).mustEmbedUnimplementedConsoleServiceServer))
}
