// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: management/v1/console/consoleService.proto

package console

import (
	rom "github.com/AyuuSaxena/protos-go/content/v1/rom"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_management_v1_console_consoleService_proto protoreflect.FileDescriptor

const file_management_v1_console_consoleService_proto_rawDesc = "" +
	"\n" +
	"*management/v1/console/consoleService.proto\x12\x15management.v1.console\x1a\x1cgoogle/api/annotations.proto\x1a\x18content/v1/rom/rom.proto2\x85\x01\n" +
	"\x0eConsoleService\x12s\n" +
	"\fListConsoles\x12#.content.v1.rom.ListConsolesRequest\x1a$.content.v1.rom.ListConsolesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/consolesB?Z=github.com/AyuuSaxena/protos-go/management/v1/console;consoleb\x06proto3"

var file_management_v1_console_consoleService_proto_goTypes = []any{
	(*rom.ListConsolesRequest)(nil),  // 0: content.v1.rom.ListConsolesRequest
	(*rom.ListConsolesResponse)(nil), // 1: content.v1.rom.ListConsolesResponse
}
var file_management_v1_console_consoleService_proto_depIdxs = []int32{
	0, // 0: management.v1.console.ConsoleService.ListConsoles:input_type -> content.v1.rom.ListConsolesRequest
	1, // 1: management.v1.console.ConsoleService.ListConsoles:output_type -> content.v1.rom.ListConsolesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_management_v1_console_consoleService_proto_init() }
func file_management_v1_console_consoleService_proto_init() {
	if File_management_v1_console_consoleService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_v1_console_consoleService_proto_rawDesc), len(file_management_v1_console_consoleService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_v1_console_consoleService_proto_goTypes,
		DependencyIndexes: file_management_v1_console_consoleService_proto_depIdxs,
	}.Build()
	File_management_v1_console_consoleService_proto = out.File
	file_management_v1_console_consoleService_proto_goTypes = nil
	file_management_v1_console_consoleService_proto_depIdxs = nil
}
