// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: management/v1/console/consoleService.proto

package console

import (
	context "context"
	rom "github.com/AyuuSaxena/protos-go/content/v1/rom"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleService_ListConsoles_FullMethodName = "/management.v1.console.ConsoleService/ListConsoles"
)

// ConsoleServiceClient is the client API for ConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConsoleService is the public BFF gRPC interface for gaming platform taxonomy.
// All methods are public (no authentication required), mirroring REST OptionalAuth semantics.
type ConsoleServiceClient interface {
	// ListConsoles returns supported gaming platforms/consoles for end users.
	ListConsoles(ctx context.Context, in *rom.ListConsolesRequest, opts ...grpc.CallOption) (*rom.ListConsolesResponse, error)
}

type consoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleServiceClient(cc grpc.ClientConnInterface) ConsoleServiceClient {
	return &consoleServiceClient{cc}
}

func (c *consoleServiceClient) ListConsoles(ctx context.Context, in *rom.ListConsolesRequest, opts ...grpc.CallOption) (*rom.ListConsolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rom.ListConsolesResponse)
	err := c.cc.Invoke(ctx, ConsoleService_ListConsoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleServiceServer is the server API for ConsoleService service.
// All implementations must embed UnimplementedConsoleServiceServer
// for forward compatibility.
//
// ConsoleService is the public BFF gRPC interface for gaming platform taxonomy.
// All methods are public (no authentication required), mirroring REST OptionalAuth semantics.
type ConsoleServiceServer interface {
	// ListConsoles returns supported gaming platforms/consoles for end users.
	ListConsoles(context.Context, *rom.ListConsolesRequest) (*rom.ListConsolesResponse, error)
	mustEmbedUnimplementedConsoleServiceServer()
}

// UnimplementedConsoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleServiceServer struct{}

func (UnimplementedConsoleServiceServer) ListConsoles(context.Context, *rom.ListConsolesRequest) (*rom.ListConsolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsoles not implemented")
}
func (UnimplementedConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {}
func (UnimplementedConsoleServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServiceServer will
// result in compilation errors.
type UnsafeConsoleServiceServer interface {
	mustEmbedUnimplementedConsoleServiceServer()
}

func RegisterConsoleServiceServer(s grpc.ServiceRegistrar, srv ConsoleServiceServer) {
	// If the following call panics, it indicates UnimplementedConsoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleService_ServiceDesc, srv)
}

func _ConsoleService_ListConsoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rom.ListConsolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).ListConsoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_ListConsoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).ListConsoles(ctx, req.(*rom.ListConsolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleService_ServiceDesc is the grpc.ServiceDesc for ConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "management.v1.console.ConsoleService",
	HandlerType: (*ConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConsoles",
			Handler:    _ConsoleService_ListConsoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/v1/console/consoleService.proto",
}
