// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: content/v1/rom/rom.proto

package rom

import (
	image "github.com/AyuuSaxena/protos-go/content/v1/image"
	v1 "github.com/AyuuSaxena/protos-go/storage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rom represents the core normalized ROM entity with relational IDs.
type Rom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB internal record identifier (_id)
	// @gotags: `json:"mongoId,omitempty" bson:"_id,omitempty"`
	MongoId string `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongoId,omitempty" bson:"_id,omitempty"`
	// Unique ROM identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Display title of the ROM
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// URL-friendly permalink
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty"`
	Permalink string `protobuf:"bytes,5,opt,name=permalink,proto3" json:"permalink,omitempty" bson:"permalink,omitempty"`
	// Detailed description
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Console system database ID
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	ConsoleId string `protobuf:"bytes,7,opt,name=console_id,json=consoleId,proto3" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	// Relational Foreign Key to storage file
	// @gotags: `json:"fileId,omitempty" bson:"fileId,omitempty"`
	FileId string `protobuf:"bytes,8,opt,name=file_id,json=fileId,proto3" json:"fileId,omitempty" bson:"fileId,omitempty"`
	// Game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty"`
	Publisher string `protobuf:"bytes,10,opt,name=publisher,proto3" json:"publisher,omitempty" bson:"publisher,omitempty"`
	// Release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32 `protobuf:"varint,11,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	// Game genre
	Genre string `protobuf:"bytes,12,opt,name=genre,proto3" json:"genre,omitempty"`
	// Release region
	Region string `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	// Supported players
	Players int32 `protobuf:"varint,14,opt,name=players,proto3" json:"players,omitempty"`
	// Content rating
	Rating string `protobuf:"bytes,15,opt,name=rating,proto3" json:"rating,omitempty"`
	// Category tags
	Tags []string `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,17,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Lifecycle status (active, archived, draft)
	Status string `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	// Uploader user ID
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,19,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// Created timestamp
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// Updated timestamp
	// @gotags: `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	// Publication status flag
	// @gotags: `json:"isPublish" bson:"isPublish"`
	IsPublish bool `protobuf:"varint,26,opt,name=is_publish,json=isPublish,proto3" json:"isPublish" bson:"isPublish"`
	// Active status flag (false indicates archived/deactivated)
	// @gotags: `json:"isActive" bson:"isActive"`
	IsActive bool `protobuf:"varint,27,opt,name=is_active,json=isActive,proto3" json:"isActive" bson:"isActive"`
	// Array of image groups categorized by aspect ratio.
	// Stores image IDs in DB and enriched images on read.
	// @gotags: `json:"images,omitempty" bson:"images,omitempty"`
	Images        []*image.AspectRatioImages `protobuf:"bytes,25,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rom) Reset() {
	*x = Rom{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rom) ProtoMessage() {}

func (x *Rom) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rom.ProtoReflect.Descriptor instead.
func (*Rom) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{0}
}

func (x *Rom) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *Rom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rom) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *Rom) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Rom) GetPermalink() string {
	if x != nil {
		return x.Permalink
	}
	return ""
}

func (x *Rom) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rom) GetConsoleId() string {
	if x != nil {
		return x.ConsoleId
	}
	return ""
}

func (x *Rom) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Rom) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Rom) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Rom) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Rom) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Rom) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *Rom) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *Rom) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Rom) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Rom) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Rom) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *Rom) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Rom) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Rom) GetIsPublish() bool {
	if x != nil {
		return x.IsPublish
	}
	return false
}

func (x *Rom) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Rom) GetImages() []*image.AspectRatioImages {
	if x != nil {
		return x.Images
	}
	return nil
}

type RomGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM unique identifier
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,2,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomGetRequest) Reset() {
	*x = RomGetRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomGetRequest) ProtoMessage() {}

func (x *RomGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomGetRequest.ProtoReflect.Descriptor instead.
func (*RomGetRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{1}
}

func (x *RomGetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomGetRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type RomDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM unique identifier
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// ROM name to match
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site *string `protobuf:"bytes,4,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	// Optional permalink to match
	// @gotags: `form:"permalink" json:"permalink,omitempty"`
	Permalink     *string `protobuf:"bytes,5,opt,name=permalink,proto3,oneof" json:"permalink,omitempty" form:"permalink"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDownloadRequest) Reset() {
	*x = RomDownloadRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDownloadRequest) ProtoMessage() {}

func (x *RomDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDownloadRequest.ProtoReflect.Descriptor instead.
func (*RomDownloadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{2}
}

func (x *RomDownloadRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomDownloadRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomDownloadRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomDownloadRequest) GetPermalink() string {
	if x != nil && x.Permalink != nil {
		return *x.Permalink
	}
	return ""
}

type RomQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by ROM name (partial or exact)
	// @gotags: `form:"name" json:"name,omitempty" bson:"name,omitempty"`
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty" form:"name" bson:"name,omitempty"`
	// Filter by console database ID
	// @gotags: `form:"consoleId" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	ConsoleId *string `protobuf:"bytes,2,opt,name=console_id,json=consoleId,proto3,oneof" json:"consoleId,omitempty" form:"consoleId" bson:"consoleId,omitempty"`
	// Filter by ROM extension (e.g. gba, snes, nds, psx)
	// @gotags: `form:"romExtension" json:"romExtension,omitempty" bson:"romExtension,omitempty"`
	RomExtension *string `protobuf:"bytes,3,opt,name=rom_extension,json=romExtension,proto3,oneof" json:"romExtension,omitempty" form:"romExtension" bson:"romExtension,omitempty"`
	// Filter by genre
	// @gotags: `form:"genre" json:"genre,omitempty" bson:"genre,omitempty"`
	Genre *string `protobuf:"bytes,4,opt,name=genre,proto3,oneof" json:"genre,omitempty" form:"genre" bson:"genre,omitempty"`
	// Filter by release region (e.g. USA, EUR, JPN)
	// @gotags: `form:"region" json:"region,omitempty" bson:"region,omitempty"`
	Region *string `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty" form:"region" bson:"region,omitempty"`
	// Filter by content status (e.g. active, archived)
	// @gotags: `form:"status" json:"status,omitempty" bson:"status,omitempty"`
	Status *string `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status" bson:"status,omitempty"`
	// Filter by public visibility
	// @gotags: `form:"isPublic" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic *bool `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" form:"isPublic" bson:"isPublic,omitempty"`
	// Filter by tag
	// @gotags: `form:"tag" json:"tag,omitempty" bson:"tag,omitempty"`
	Tag *string `protobuf:"bytes,8,opt,name=tag,proto3,oneof" json:"tag,omitempty" form:"tag" bson:"tag,omitempty"`
	// Filter by uploader user ID
	// @gotags: `form:"uploaderId" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId *string `protobuf:"bytes,9,opt,name=uploader_id,json=uploaderId,proto3,oneof" json:"uploaderId,omitempty" form:"uploaderId" bson:"uploaderId,omitempty"`
	// Filter by site key (e.g. retrogames)
	// @gotags: `form:"site" json:"site,omitempty" bson:"site,omitempty"`
	Site *string `protobuf:"bytes,10,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site" bson:"site,omitempty"`
	// Filter by publication status
	// @gotags: `form:"isPublish" json:"isPublish,omitempty" bson:"isPublish,omitempty"`
	IsPublish *bool `protobuf:"varint,11,opt,name=is_publish,json=isPublish,proto3,oneof" json:"isPublish,omitempty" form:"isPublish" bson:"isPublish,omitempty"`
	// Filter by active status
	// @gotags: `form:"isActive" json:"isActive,omitempty" bson:"isActive,omitempty"`
	IsActive      *bool `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3,oneof" json:"isActive,omitempty" form:"isActive" bson:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomQuery) Reset() {
	*x = RomQuery{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomQuery) ProtoMessage() {}

func (x *RomQuery) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomQuery.ProtoReflect.Descriptor instead.
func (*RomQuery) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{3}
}

func (x *RomQuery) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomQuery) GetConsoleId() string {
	if x != nil && x.ConsoleId != nil {
		return *x.ConsoleId
	}
	return ""
}

func (x *RomQuery) GetRomExtension() string {
	if x != nil && x.RomExtension != nil {
		return *x.RomExtension
	}
	return ""
}

func (x *RomQuery) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *RomQuery) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *RomQuery) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *RomQuery) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *RomQuery) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *RomQuery) GetUploaderId() string {
	if x != nil && x.UploaderId != nil {
		return *x.UploaderId
	}
	return ""
}

func (x *RomQuery) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomQuery) GetIsPublish() bool {
	if x != nil && x.IsPublish != nil {
		return *x.IsPublish
	}
	return false
}

func (x *RomQuery) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type RomSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of items to return (default 20, max 100)
	// @gotags: `form:"limit" json:"limit,omitempty" bson:"limit,omitempty"`
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty" form:"limit" bson:"limit,omitempty"`
	// Number of items to skip for pagination (default 0)
	// @gotags: `form:"offset" json:"offset,omitempty" bson:"offset,omitempty"`
	Offset *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty" form:"offset" bson:"offset,omitempty"`
	// Keyword search across title, description, and tags
	// @gotags: `form:"keyword" json:"keyword,omitempty" bson:"keyword,omitempty"`
	Keyword *string `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty" form:"keyword" bson:"keyword,omitempty"`
	// Field name to sort by (e.g. title, createdAt, releaseYear)
	// @gotags: `form:"sortby" json:"sortby,omitempty" bson:"sortby,omitempty"`
	Sortby *string `protobuf:"bytes,4,opt,name=sortby,proto3,oneof" json:"sortby,omitempty" form:"sortby" bson:"sortby,omitempty"`
	// Sort direction order (asc or desc, default desc)
	// @gotags: `form:"sortOrder" json:"sortOrder,omitempty" bson:"sortOrder,omitempty"`
	SortOrder *string `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sortOrder,omitempty" form:"sortOrder" bson:"sortOrder,omitempty"`
	// Nested query filters for ROM properties
	// @gotags: `json:"query,omitempty" bson:"query,omitempty"`
	Query *RomQuery `protobuf:"bytes,6,opt,name=query,proto3,oneof" json:"query,omitempty" bson:"query,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty" bson:"site,omitempty"`
	Site          *string `protobuf:"bytes,7,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site" bson:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomSearchRequest) Reset() {
	*x = RomSearchRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomSearchRequest) ProtoMessage() {}

func (x *RomSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomSearchRequest.ProtoReflect.Descriptor instead.
func (*RomSearchRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{4}
}

func (x *RomSearchRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *RomSearchRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *RomSearchRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *RomSearchRequest) GetSortby() string {
	if x != nil && x.Sortby != nil {
		return *x.Sortby
	}
	return ""
}

func (x *RomSearchRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

func (x *RomSearchRequest) GetQuery() *RomQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RomSearchRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

// RomCreateOrUpdateRequest is used for both creating and updating
// a ROM.
//
// For create:
// - id is omitted
// - ROM fields are provided
//
// For update:
// - id is provided
// - only fields that need to be updated are provided.
type RomCreateOrUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM unique identifier.
	// Required for update and omitted for create.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty" form:"site"`
	Site *string `protobuf:"bytes,2,opt,name=site,proto3,oneof" json:"site,omitempty" bson:"site,omitempty" form:"site"`
	// ROM display title
	Title *string `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// ROM description
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Console system database ID
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty" form:"consoleId"`
	ConsoleId *string `protobuf:"bytes,5,opt,name=console_id,json=consoleId,proto3,oneof" json:"consoleId,omitempty" bson:"consoleId,omitempty" form:"consoleId"`
	// ROM extension (e.g. gba, snes, nds, psx)
	// @gotags: `json:"romExtension,omitempty" bson:"romExtension,omitempty" form:"romExtension"`
	RomExtension *string `protobuf:"bytes,6,opt,name=rom_extension,json=romExtension,proto3,oneof" json:"romExtension,omitempty" bson:"romExtension,omitempty" form:"romExtension"`
	// URL-friendly permalink
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty" form:"permalink"`
	Permalink *string `protobuf:"bytes,7,opt,name=permalink,proto3,oneof" json:"permalink,omitempty" bson:"permalink,omitempty" form:"permalink"`
	// Game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty" form:"publisher"`
	Publisher *string `protobuf:"bytes,8,opt,name=publisher,proto3,oneof" json:"publisher,omitempty" bson:"publisher,omitempty" form:"publisher"`
	// Release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty" form:"releaseYear"`
	ReleaseYear *int32 `protobuf:"varint,9,opt,name=release_year,json=releaseYear,proto3,oneof" json:"releaseYear,omitempty" bson:"releaseYear,omitempty" form:"releaseYear"`
	// Game genre
	Genre *string `protobuf:"bytes,10,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	// Release region
	Region *string `protobuf:"bytes,11,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// Supported players
	Players *int32 `protobuf:"varint,12,opt,name=players,proto3,oneof" json:"players,omitempty"`
	// Content rating
	Rating *string `protobuf:"bytes,13,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	// Category tags
	Tags []string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty" form:"isPublic"`
	IsPublic *bool `protobuf:"varint,15,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" bson:"isPublic,omitempty" form:"isPublic"`
	// Uploader user ID
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId *string `protobuf:"bytes,16,opt,name=uploader_id,json=uploaderId,proto3,oneof" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// Array of image groups categorized by aspect ratio
	// @gotags: `json:"images,omitempty" bson:"images,omitempty" form:"images"`
	Images []*image.AspectRatioImages `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty" form:"images"`
	// Publication status flag
	// @gotags: `json:"isPublish,omitempty" bson:"isPublish,omitempty" form:"isPublish"`
	IsPublish *bool `protobuf:"varint,18,opt,name=is_publish,json=isPublish,proto3,oneof" json:"isPublish,omitempty" bson:"isPublish,omitempty" form:"isPublish"`
	// Active status flag
	// @gotags: `json:"isActive,omitempty" bson:"isActive,omitempty" form:"isActive"`
	IsActive      *bool `protobuf:"varint,19,opt,name=is_active,json=isActive,proto3,oneof" json:"isActive,omitempty" bson:"isActive,omitempty" form:"isActive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomCreateOrUpdateRequest) Reset() {
	*x = RomCreateOrUpdateRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomCreateOrUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomCreateOrUpdateRequest) ProtoMessage() {}

func (x *RomCreateOrUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomCreateOrUpdateRequest.ProtoReflect.Descriptor instead.
func (*RomCreateOrUpdateRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{5}
}

func (x *RomCreateOrUpdateRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetConsoleId() string {
	if x != nil && x.ConsoleId != nil {
		return *x.ConsoleId
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetRomExtension() string {
	if x != nil && x.RomExtension != nil {
		return *x.RomExtension
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetPermalink() string {
	if x != nil && x.Permalink != nil {
		return *x.Permalink
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetPublisher() string {
	if x != nil && x.Publisher != nil {
		return *x.Publisher
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetReleaseYear() int32 {
	if x != nil && x.ReleaseYear != nil {
		return *x.ReleaseYear
	}
	return 0
}

func (x *RomCreateOrUpdateRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetPlayers() int32 {
	if x != nil && x.Players != nil {
		return *x.Players
	}
	return 0
}

func (x *RomCreateOrUpdateRequest) GetRating() string {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RomCreateOrUpdateRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *RomCreateOrUpdateRequest) GetUploaderId() string {
	if x != nil && x.UploaderId != nil {
		return *x.UploaderId
	}
	return ""
}

func (x *RomCreateOrUpdateRequest) GetImages() []*image.AspectRatioImages {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *RomCreateOrUpdateRequest) GetIsPublish() bool {
	if x != nil && x.IsPublish != nil {
		return *x.IsPublish
	}
	return false
}

func (x *RomCreateOrUpdateRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type RomUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestData:
	//
	//	*RomUploadRequest_Rom
	//	*RomUploadRequest_ChunkData
	RequestData   isRomUploadRequest_RequestData `protobuf_oneof:"request_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUploadRequest) Reset() {
	*x = RomUploadRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadRequest) ProtoMessage() {}

func (x *RomUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadRequest.ProtoReflect.Descriptor instead.
func (*RomUploadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{6}
}

func (x *RomUploadRequest) GetRequestData() isRomUploadRequest_RequestData {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *RomUploadRequest) GetRom() *RomCreateOrUpdateRequest {
	if x != nil {
		if x, ok := x.RequestData.(*RomUploadRequest_Rom); ok {
			return x.Rom
		}
	}
	return nil
}

func (x *RomUploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.RequestData.(*RomUploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isRomUploadRequest_RequestData interface {
	isRomUploadRequest_RequestData()
}

type RomUploadRequest_Rom struct {
	// ROM metadata for initial chunk
	// @gotags: `json:"rom,omitempty" bson:"rom,omitempty"`
	Rom *RomCreateOrUpdateRequest `protobuf:"bytes,1,opt,name=rom,proto3,oneof" json:"rom,omitempty" bson:"rom,omitempty"`
}

type RomUploadRequest_ChunkData struct {
	// Binary chunk data
	// @gotags: `json:"chunkData,omitempty" bson:"chunkData,omitempty"`
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof" json:"chunkData,omitempty" bson:"chunkData,omitempty"`
}

func (*RomUploadRequest_Rom) isRomUploadRequest_RequestData() {}

func (*RomUploadRequest_ChunkData) isRomUploadRequest_RequestData() {}

type RomDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ROM identifier to delete
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Hard delete flag (permanently remove file from storage and database)
	// @gotags: `json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	HardDelete bool `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,3,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDeleteRequest) Reset() {
	*x = RomDeleteRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDeleteRequest) ProtoMessage() {}

func (x *RomDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDeleteRequest.ProtoReflect.Descriptor instead.
func (*RomDeleteRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{7}
}

func (x *RomDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomDeleteRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

func (x *RomDeleteRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type RomShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ROM identifier to share
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pre-signed download URL expiration duration in seconds
	// @gotags: `json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	ExpiresInSec int32 `protobuf:"varint,2,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,3,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomShareRequest) Reset() {
	*x = RomShareRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomShareRequest) ProtoMessage() {}

func (x *RomShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomShareRequest.ProtoReflect.Descriptor instead.
func (*RomShareRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{8}
}

func (x *RomShareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomShareRequest) GetExpiresInSec() int32 {
	if x != nil {
		return x.ExpiresInSec
	}
	return 0
}

func (x *RomShareRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type RomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ROM identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Display title of the ROM
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// URL-friendly permalink
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty"`
	Permalink string `protobuf:"bytes,5,opt,name=permalink,proto3" json:"permalink,omitempty" bson:"permalink,omitempty"`
	// Detailed description
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Console system database ID
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	Console *ConsoleInfo `protobuf:"bytes,7,opt,name=console,proto3" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	// Relational Foreign Key to storage file
	// @gotags: `json:"file,omitempty" bson:"file,omitempty"`
	File *v1.FileResponse `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty" bson:"file,omitempty"`
	// Game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty"`
	Publisher string `protobuf:"bytes,10,opt,name=publisher,proto3" json:"publisher,omitempty" bson:"publisher,omitempty"`
	// Release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32 `protobuf:"varint,11,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	// Game genre
	Genre string `protobuf:"bytes,12,opt,name=genre,proto3" json:"genre,omitempty"`
	// Release region
	Region string `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	// Supported players
	Players int32 `protobuf:"varint,14,opt,name=players,proto3" json:"players,omitempty"`
	// Content rating
	Rating string `protobuf:"bytes,15,opt,name=rating,proto3" json:"rating,omitempty"`
	// Category tags
	Tags []string `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,17,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Lifecycle status (active, archived, draft)
	Status string `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	// Uploader user ID
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,19,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// Created timestamp
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// Updated timestamp
	// @gotags: `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	// Publication status flag
	// @gotags: `json:"isPublish" bson:"isPublish"`
	IsPublish bool `protobuf:"varint,26,opt,name=is_publish,json=isPublish,proto3" json:"isPublish" bson:"isPublish"`
	// Active status flag (false indicates archived/deactivated)
	// @gotags: `json:"isActive" bson:"isActive"`
	IsActive bool `protobuf:"varint,27,opt,name=is_active,json=isActive,proto3" json:"isActive" bson:"isActive"`
	// Array of image groups categorized by aspect ratio.
	// Stores image IDs in DB and enriched images on read.
	// @gotags: `json:"images,omitempty" bson:"images,omitempty"`
	Images        []*image.AspectRatioImagesResponse `protobuf:"bytes,25,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomResponse) Reset() {
	*x = RomResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomResponse) ProtoMessage() {}

func (x *RomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomResponse.ProtoReflect.Descriptor instead.
func (*RomResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{9}
}

func (x *RomResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomResponse) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RomResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RomResponse) GetPermalink() string {
	if x != nil {
		return x.Permalink
	}
	return ""
}

func (x *RomResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RomResponse) GetConsole() *ConsoleInfo {
	if x != nil {
		return x.Console
	}
	return nil
}

func (x *RomResponse) GetFile() *v1.FileResponse {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *RomResponse) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *RomResponse) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *RomResponse) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *RomResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RomResponse) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *RomResponse) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *RomResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RomResponse) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *RomResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RomResponse) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *RomResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RomResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RomResponse) GetIsPublish() bool {
	if x != nil {
		return x.IsPublish
	}
	return false
}

func (x *RomResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RomResponse) GetImages() []*image.AspectRatioImagesResponse {
	if x != nil {
		return x.Images
	}
	return nil
}

type RomSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of ROM metadata items for the current page
	Roms []*Rom `protobuf:"bytes,1,rep,name=roms,proto3" json:"roms,omitempty"`
	// Total count of items matching the query
	// @gotags: `json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	TotalCount int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	// Page size limit applied
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset applied
	Offset int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Calculated total number of pages
	// @gotags: `json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	TotalPages    int32 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomSearchResponse) Reset() {
	*x = RomSearchResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomSearchResponse) ProtoMessage() {}

func (x *RomSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomSearchResponse.ProtoReflect.Descriptor instead.
func (*RomSearchResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{10}
}

func (x *RomSearchResponse) GetRoms() []*Rom {
	if x != nil {
		return x.Roms
	}
	return nil
}

func (x *RomSearchResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RomSearchResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RomSearchResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RomSearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type RomUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uploaded ROM metadata
	Rom *Rom `protobuf:"bytes,1,opt,name=rom,proto3" json:"rom,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUploadResponse) Reset() {
	*x = RomUploadResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadResponse) ProtoMessage() {}

func (x *RomUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadResponse.ProtoReflect.Descriptor instead.
func (*RomUploadResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{11}
}

func (x *RomUploadResponse) GetRom() *Rom {
	if x != nil {
		return x.Rom
	}
	return nil
}

func (x *RomUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RomDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDeleteResponse) Reset() {
	*x = RomDeleteResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDeleteResponse) ProtoMessage() {}

func (x *RomDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDeleteResponse.ProtoReflect.Descriptor instead.
func (*RomDeleteResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{12}
}

func (x *RomDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RomDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RomShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Generated pre-signed download URL
	// @gotags: `json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	// ISO-8601 expiration timestamp
	// @gotags: `json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	ExpiresAt string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomShareResponse) Reset() {
	*x = RomShareResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomShareResponse) ProtoMessage() {}

func (x *RomShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomShareResponse.ProtoReflect.Descriptor instead.
func (*RomShareResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{13}
}

func (x *RomShareResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomShareResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *RomShareResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RomShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_content_v1_rom_rom_proto protoreflect.FileDescriptor

const file_content_v1_rom_rom_proto_rawDesc = "" +
	"\n" +
	"\x18content/v1/rom/rom.proto\x12\x0econtent.v1.rom\x1a\x1ccontent/v1/image/image.proto\x1a\x1ccontent/v1/rom/console.proto\x1a\x18storage/v1/storage.proto\"\x94\x05\n" +
	"\x03Rom\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tpermalink\x18\x05 \x01(\tR\tpermalink\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"console_id\x18\a \x01(\tR\tconsoleId\x12\x17\n" +
	"\afile_id\x18\b \x01(\tR\x06fileId\x12\x1c\n" +
	"\tpublisher\x18\n" +
	" \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\v \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\f \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\r \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\x0e \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\x0f \x01(\tR\x06rating\x12\x12\n" +
	"\x04tags\x18\x10 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x11 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12\x1f\n" +
	"\vuploader_id\x18\x13 \x01(\tR\n" +
	"uploaderId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x15 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_publish\x18\x1a \x01(\bR\tisPublish\x12\x1b\n" +
	"\tis_active\x18\x1b \x01(\bR\bisActive\x12;\n" +
	"\x06images\x18\x19 \x03(\v2#.content.v1.image.AspectRatioImagesR\x06images\"M\n" +
	"\rRomGetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x02 \x01(\tH\x01R\x04site\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_site\"\xa5\x01\n" +
	"\x12RomDownloadRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x04 \x01(\tH\x02R\x04site\x88\x01\x01\x12!\n" +
	"\tpermalink\x18\x05 \x01(\tH\x03R\tpermalink\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_siteB\f\n" +
	"\n" +
	"_permalink\"\x9a\x04\n" +
	"\bRomQuery\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"console_id\x18\x02 \x01(\tH\x01R\tconsoleId\x88\x01\x01\x12(\n" +
	"\rrom_extension\x18\x03 \x01(\tH\x02R\fromExtension\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\x04 \x01(\tH\x03R\x05genre\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x04R\x06region\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x05R\x06status\x88\x01\x01\x12 \n" +
	"\tis_public\x18\a \x01(\bH\x06R\bisPublic\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\b \x01(\tH\aR\x03tag\x88\x01\x01\x12$\n" +
	"\vuploader_id\x18\t \x01(\tH\bR\n" +
	"uploaderId\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\n" +
	" \x01(\tH\tR\x04site\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_publish\x18\v \x01(\bH\n" +
	"R\tisPublish\x88\x01\x01\x12 \n" +
	"\tis_active\x18\f \x01(\bH\vR\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_console_idB\x10\n" +
	"\x0e_rom_extensionB\b\n" +
	"\x06_genreB\t\n" +
	"\a_regionB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_is_publicB\x06\n" +
	"\x04_tagB\x0e\n" +
	"\f_uploader_idB\a\n" +
	"\x05_siteB\r\n" +
	"\v_is_publishB\f\n" +
	"\n" +
	"_is_active\"\xc6\x02\n" +
	"\x10RomSearchRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01\x12\x1b\n" +
	"\x06sortby\x18\x04 \x01(\tH\x03R\x06sortby\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tH\x04R\tsortOrder\x88\x01\x01\x123\n" +
	"\x05query\x18\x06 \x01(\v2\x18.content.v1.rom.RomQueryH\x05R\x05query\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\a \x01(\tH\x06R\x04site\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\n" +
	"\n" +
	"\b_keywordB\t\n" +
	"\a_sortbyB\r\n" +
	"\v_sort_orderB\b\n" +
	"\x06_queryB\a\n" +
	"\x05_site\"\xf8\x06\n" +
	"\x18RomCreateOrUpdateRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x02 \x01(\tH\x01R\x04site\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x02R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"console_id\x18\x05 \x01(\tH\x04R\tconsoleId\x88\x01\x01\x12(\n" +
	"\rrom_extension\x18\x06 \x01(\tH\x05R\fromExtension\x88\x01\x01\x12!\n" +
	"\tpermalink\x18\a \x01(\tH\x06R\tpermalink\x88\x01\x01\x12!\n" +
	"\tpublisher\x18\b \x01(\tH\aR\tpublisher\x88\x01\x01\x12&\n" +
	"\frelease_year\x18\t \x01(\x05H\bR\vreleaseYear\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\n" +
	" \x01(\tH\tR\x05genre\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\v \x01(\tH\n" +
	"R\x06region\x88\x01\x01\x12\x1d\n" +
	"\aplayers\x18\f \x01(\x05H\vR\aplayers\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\r \x01(\tH\fR\x06rating\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12 \n" +
	"\tis_public\x18\x0f \x01(\bH\rR\bisPublic\x88\x01\x01\x12$\n" +
	"\vuploader_id\x18\x10 \x01(\tH\x0eR\n" +
	"uploaderId\x88\x01\x01\x12;\n" +
	"\x06images\x18\x11 \x03(\v2#.content.v1.image.AspectRatioImagesR\x06images\x12\"\n" +
	"\n" +
	"is_publish\x18\x12 \x01(\bH\x0fR\tisPublish\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x13 \x01(\bH\x10R\bisActive\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_siteB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_console_idB\x10\n" +
	"\x0e_rom_extensionB\f\n" +
	"\n" +
	"_permalinkB\f\n" +
	"\n" +
	"_publisherB\x0f\n" +
	"\r_release_yearB\b\n" +
	"\x06_genreB\t\n" +
	"\a_regionB\n" +
	"\n" +
	"\b_playersB\t\n" +
	"\a_ratingB\f\n" +
	"\n" +
	"_is_publicB\x0e\n" +
	"\f_uploader_idB\r\n" +
	"\v_is_publishB\f\n" +
	"\n" +
	"_is_active\"\x81\x01\n" +
	"\x10RomUploadRequest\x12<\n" +
	"\x03rom\x18\x01 \x01(\v2(.content.v1.rom.RomCreateOrUpdateRequestH\x00R\x03rom\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x0e\n" +
	"\frequest_data\"e\n" +
	"\x10RomDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\x12\x17\n" +
	"\x04site\x18\x03 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"i\n" +
	"\x0fRomShareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eexpires_in_sec\x18\x02 \x01(\x05R\fexpiresInSec\x12\x17\n" +
	"\x04site\x18\x03 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"\xb6\x05\n" +
	"\vRomResponse\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tpermalink\x18\x05 \x01(\tR\tpermalink\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x125\n" +
	"\aconsole\x18\a \x01(\v2\x1b.content.v1.rom.ConsoleInfoR\aconsole\x12,\n" +
	"\x04file\x18\b \x01(\v2\x18.storage.v1.FileResponseR\x04file\x12\x1c\n" +
	"\tpublisher\x18\n" +
	" \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\v \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\f \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\r \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\x0e \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\x0f \x01(\tR\x06rating\x12\x12\n" +
	"\x04tags\x18\x10 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x11 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12\x1f\n" +
	"\vuploader_id\x18\x13 \x01(\tR\n" +
	"uploaderId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x15 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_publish\x18\x1a \x01(\bR\tisPublish\x12\x1b\n" +
	"\tis_active\x18\x1b \x01(\bR\bisActive\x12C\n" +
	"\x06images\x18\x19 \x03(\v2+.content.v1.image.AspectRatioImagesResponseR\x06images\"\xac\x01\n" +
	"\x11RomSearchResponse\x12'\n" +
	"\x04roms\x18\x01 \x03(\v2\x13.content.v1.rom.RomR\x04roms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"T\n" +
	"\x11RomUploadResponse\x12%\n" +
	"\x03rom\x18\x01 \x01(\v2\x13.content.v1.rom.RomR\x03rom\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x11RomDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"~\n" +
	"\x10RomShareResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessageB4Z2github.com/AyuuSaxena/protos-go/content/v1/rom;romb\x06proto3"

var (
	file_content_v1_rom_rom_proto_rawDescOnce sync.Once
	file_content_v1_rom_rom_proto_rawDescData []byte
)

func file_content_v1_rom_rom_proto_rawDescGZIP() []byte {
	file_content_v1_rom_rom_proto_rawDescOnce.Do(func() {
		file_content_v1_rom_rom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_rom_rom_proto_rawDesc), len(file_content_v1_rom_rom_proto_rawDesc)))
	})
	return file_content_v1_rom_rom_proto_rawDescData
}

var file_content_v1_rom_rom_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_content_v1_rom_rom_proto_goTypes = []any{
	(*Rom)(nil),                             // 0: content.v1.rom.Rom
	(*RomGetRequest)(nil),                   // 1: content.v1.rom.RomGetRequest
	(*RomDownloadRequest)(nil),              // 2: content.v1.rom.RomDownloadRequest
	(*RomQuery)(nil),                        // 3: content.v1.rom.RomQuery
	(*RomSearchRequest)(nil),                // 4: content.v1.rom.RomSearchRequest
	(*RomCreateOrUpdateRequest)(nil),        // 5: content.v1.rom.RomCreateOrUpdateRequest
	(*RomUploadRequest)(nil),                // 6: content.v1.rom.RomUploadRequest
	(*RomDeleteRequest)(nil),                // 7: content.v1.rom.RomDeleteRequest
	(*RomShareRequest)(nil),                 // 8: content.v1.rom.RomShareRequest
	(*RomResponse)(nil),                     // 9: content.v1.rom.RomResponse
	(*RomSearchResponse)(nil),               // 10: content.v1.rom.RomSearchResponse
	(*RomUploadResponse)(nil),               // 11: content.v1.rom.RomUploadResponse
	(*RomDeleteResponse)(nil),               // 12: content.v1.rom.RomDeleteResponse
	(*RomShareResponse)(nil),                // 13: content.v1.rom.RomShareResponse
	(*image.AspectRatioImages)(nil),         // 14: content.v1.image.AspectRatioImages
	(*ConsoleInfo)(nil),                     // 15: content.v1.rom.ConsoleInfo
	(*v1.FileResponse)(nil),                 // 16: storage.v1.FileResponse
	(*image.AspectRatioImagesResponse)(nil), // 17: content.v1.image.AspectRatioImagesResponse
}
var file_content_v1_rom_rom_proto_depIdxs = []int32{
	14, // 0: content.v1.rom.Rom.images:type_name -> content.v1.image.AspectRatioImages
	3,  // 1: content.v1.rom.RomSearchRequest.query:type_name -> content.v1.rom.RomQuery
	14, // 2: content.v1.rom.RomCreateOrUpdateRequest.images:type_name -> content.v1.image.AspectRatioImages
	5,  // 3: content.v1.rom.RomUploadRequest.rom:type_name -> content.v1.rom.RomCreateOrUpdateRequest
	15, // 4: content.v1.rom.RomResponse.console:type_name -> content.v1.rom.ConsoleInfo
	16, // 5: content.v1.rom.RomResponse.file:type_name -> storage.v1.FileResponse
	17, // 6: content.v1.rom.RomResponse.images:type_name -> content.v1.image.AspectRatioImagesResponse
	0,  // 7: content.v1.rom.RomSearchResponse.roms:type_name -> content.v1.rom.Rom
	0,  // 8: content.v1.rom.RomUploadResponse.rom:type_name -> content.v1.rom.Rom
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_content_v1_rom_rom_proto_init() }
func file_content_v1_rom_rom_proto_init() {
	if File_content_v1_rom_rom_proto != nil {
		return
	}
	file_content_v1_rom_console_proto_init()
	file_content_v1_rom_rom_proto_msgTypes[1].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[2].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[3].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[4].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[5].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[6].OneofWrappers = []any{
		(*RomUploadRequest_Rom)(nil),
		(*RomUploadRequest_ChunkData)(nil),
	}
	file_content_v1_rom_rom_proto_msgTypes[7].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_rom_rom_proto_rawDesc), len(file_content_v1_rom_rom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_v1_rom_rom_proto_goTypes,
		DependencyIndexes: file_content_v1_rom_rom_proto_depIdxs,
		MessageInfos:      file_content_v1_rom_rom_proto_msgTypes,
	}.Build()
	File_content_v1_rom_rom_proto = out.File
	file_content_v1_rom_rom_proto_goTypes = nil
	file_content_v1_rom_rom_proto_depIdxs = nil
}
