// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: content/v1/rom/rom.proto

package rom

import (
	v1 "github.com/AyuuSaxena/protos-go/common/v1"
	image "github.com/AyuuSaxena/protos-go/content/v1/image"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsoleInfo represents a gaming console system stored in the database taxonomy.
type ConsoleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB internal record identifier (_id)
	// @gotags: `json:"mongoId,omitempty" bson:"_id,omitempty"`
	MongoId string `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongoId,omitempty" bson:"_id,omitempty"`
	// Unique console identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Console system key (e.g. gba, snes, nds, psx)
	Key string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// Full display name of the console
	// @gotags: `json:"fullName,omitempty" bson:"fullName,omitempty"`
	FullName string `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty" bson:"fullName,omitempty"`
	// Supported file extensions (without leading dot)
	Extensions []string `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Hardware manufacturer (e.g. Nintendo, Sony, Sega)
	Manufacturer string `protobuf:"bytes,8,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// Release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32 `protobuf:"varint,9,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	// Console icon or logo URL
	// @gotags: `json:"iconUrl,omitempty" bson:"iconUrl,omitempty"`
	IconUrl string `protobuf:"bytes,10,opt,name=icon_url,json=iconUrl,proto3" json:"iconUrl,omitempty" bson:"iconUrl,omitempty"`
	// Total number of ROMs linked to this console
	// @gotags: `json:"contentCount,omitempty" bson:"contentCount,omitempty"`
	ContentCount int64 `protobuf:"varint,11,opt,name=content_count,json=contentCount,proto3" json:"contentCount,omitempty" bson:"contentCount,omitempty"`
	// Creation timestamp
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// Last update timestamp
	// @gotags: `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	UpdatedAt     string `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleInfo) Reset() {
	*x = ConsoleInfo{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInfo) ProtoMessage() {}

func (x *ConsoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInfo.ProtoReflect.Descriptor instead.
func (*ConsoleInfo) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{0}
}

func (x *ConsoleInfo) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *ConsoleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsoleInfo) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ConsoleInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConsoleInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ConsoleInfo) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *ConsoleInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *ConsoleInfo) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *ConsoleInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ConsoleInfo) GetContentCount() int64 {
	if x != nil {
		return x.ContentCount
	}
	return 0
}

func (x *ConsoleInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConsoleInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// RomMetadata represents the core normalized ROM entity with relational IDs.
type RomMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB internal record identifier (_id)
	// @gotags: `json:"mongoId,omitempty" bson:"_id,omitempty"`
	MongoId string `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongoId,omitempty" bson:"_id,omitempty"`
	// Unique ROM identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Display title of the ROM
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// URL-friendly permalink
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty"`
	Permalink string `protobuf:"bytes,5,opt,name=permalink,proto3" json:"permalink,omitempty" bson:"permalink,omitempty"`
	// Detailed description
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Relational Foreign Keys
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	ConsoleId string `protobuf:"bytes,7,opt,name=console_id,json=consoleId,proto3" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	// @gotags: `json:"fileId,omitempty" bson:"fileId,omitempty"`
	FileId string `protobuf:"bytes,8,opt,name=file_id,json=fileId,proto3" json:"fileId,omitempty" bson:"fileId,omitempty"`
	// Game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty"`
	Publisher string `protobuf:"bytes,10,opt,name=publisher,proto3" json:"publisher,omitempty" bson:"publisher,omitempty"`
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32    `protobuf:"varint,11,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	Genre       string   `protobuf:"bytes,12,opt,name=genre,proto3" json:"genre,omitempty"`
	Region      string   `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Players     int32    `protobuf:"varint,14,opt,name=players,proto3" json:"players,omitempty"`
	Rating      string   `protobuf:"bytes,15,opt,name=rating,proto3" json:"rating,omitempty"`
	Tags        []string `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,17,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Lifecycle status (active, archived, draft)
	Status string `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,19,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// @gotags: `json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	UploaderUsername string `protobuf:"bytes,20,opt,name=uploader_username,json=uploaderUsername,proto3" json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// @gotags: `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	// Enriched Relations (populated on read, not persisted in DB)
	// Full console details resolved from consoleId
	// @gotags: `json:"consoleMetadata,omitempty" bson:"consoleMetadata,omitempty"`
	ConsoleMetadata *ConsoleInfo `protobuf:"bytes,23,opt,name=console_metadata,json=consoleMetadata,proto3" json:"consoleMetadata,omitempty" bson:"consoleMetadata,omitempty"`
	// Full file details resolved from fileId
	// @gotags: `json:"fileMetadata,omitempty" bson:"fileMetadata,omitempty"`
	FileMetadata *v1.FileMetadata `protobuf:"bytes,24,opt,name=file_metadata,json=fileMetadata,proto3" json:"fileMetadata,omitempty" bson:"fileMetadata,omitempty"`
	// Array of image groups categorized by aspect ratio, storing imageIds in DB and enriched images on read
	// @gotags: `json:"images,omitempty" bson:"images,omitempty"`
	Images []*image.AspectRatioImages `protobuf:"bytes,25,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty"`
	// Publication status flag
	// @gotags: `json:"isPublish" bson:"isPublish"`
	IsPublish bool `protobuf:"varint,26,opt,name=is_publish,json=isPublish,proto3" json:"isPublish" bson:"isPublish"`
	// Active status flag (false indicates archived/deactivated)
	// @gotags: `json:"isActive" bson:"isActive"`
	IsActive      bool `protobuf:"varint,27,opt,name=is_active,json=isActive,proto3" json:"isActive" bson:"isActive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomMetadata) Reset() {
	*x = RomMetadata{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomMetadata) ProtoMessage() {}

func (x *RomMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomMetadata.ProtoReflect.Descriptor instead.
func (*RomMetadata) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{1}
}

func (x *RomMetadata) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *RomMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomMetadata) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RomMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RomMetadata) GetPermalink() string {
	if x != nil {
		return x.Permalink
	}
	return ""
}

func (x *RomMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RomMetadata) GetConsoleId() string {
	if x != nil {
		return x.ConsoleId
	}
	return ""
}

func (x *RomMetadata) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RomMetadata) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *RomMetadata) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *RomMetadata) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *RomMetadata) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RomMetadata) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *RomMetadata) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *RomMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RomMetadata) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *RomMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RomMetadata) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *RomMetadata) GetUploaderUsername() string {
	if x != nil {
		return x.UploaderUsername
	}
	return ""
}

func (x *RomMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RomMetadata) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RomMetadata) GetConsoleMetadata() *ConsoleInfo {
	if x != nil {
		return x.ConsoleMetadata
	}
	return nil
}

func (x *RomMetadata) GetFileMetadata() *v1.FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

func (x *RomMetadata) GetImages() []*image.AspectRatioImages {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *RomMetadata) GetIsPublish() bool {
	if x != nil {
		return x.IsPublish
	}
	return false
}

func (x *RomMetadata) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type RomGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM unique identifier
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// ROM name to match
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site *string `protobuf:"bytes,4,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	// Optional permalink to match
	// @gotags: `form:"permalink" json:"permalink,omitempty"`
	Permalink     *string `protobuf:"bytes,5,opt,name=permalink,proto3,oneof" json:"permalink,omitempty" form:"permalink"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomGetRequest) Reset() {
	*x = RomGetRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomGetRequest) ProtoMessage() {}

func (x *RomGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomGetRequest.ProtoReflect.Descriptor instead.
func (*RomGetRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{2}
}

func (x *RomGetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomGetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomGetRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomGetRequest) GetPermalink() string {
	if x != nil && x.Permalink != nil {
		return *x.Permalink
	}
	return ""
}

type RomDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM unique identifier
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// ROM name to match
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site *string `protobuf:"bytes,4,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	// Optional permalink to match
	// @gotags: `form:"permalink" json:"permalink,omitempty"`
	Permalink     *string `protobuf:"bytes,5,opt,name=permalink,proto3,oneof" json:"permalink,omitempty" form:"permalink"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDownloadRequest) Reset() {
	*x = RomDownloadRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDownloadRequest) ProtoMessage() {}

func (x *RomDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDownloadRequest.ProtoReflect.Descriptor instead.
func (*RomDownloadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{3}
}

func (x *RomDownloadRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomDownloadRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomDownloadRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomDownloadRequest) GetPermalink() string {
	if x != nil && x.Permalink != nil {
		return *x.Permalink
	}
	return ""
}

type RomQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by ROM name (partial or exact)
	// @gotags: `form:"name" json:"name,omitempty" bson:"name,omitempty"`
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty" form:"name" bson:"name,omitempty"`
	// Filter by console database ID
	// @gotags: `form:"consoleId" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	ConsoleId *string `protobuf:"bytes,2,opt,name=console_id,json=consoleId,proto3,oneof" json:"consoleId,omitempty" form:"consoleId" bson:"consoleId,omitempty"`
	// Filter by console key (e.g. gba, snes, nds, psx)
	// @gotags: `form:"consoleKey" json:"consoleKey,omitempty" bson:"consoleKey,omitempty"`
	ConsoleKey *string `protobuf:"bytes,3,opt,name=console_key,json=consoleKey,proto3,oneof" json:"consoleKey,omitempty" form:"consoleKey" bson:"consoleKey,omitempty"`
	// Filter by genre
	// @gotags: `form:"genre" json:"genre,omitempty" bson:"genre,omitempty"`
	Genre *string `protobuf:"bytes,4,opt,name=genre,proto3,oneof" json:"genre,omitempty" form:"genre" bson:"genre,omitempty"`
	// Filter by release region (e.g. USA, EUR, JPN)
	// @gotags: `form:"region" json:"region,omitempty" bson:"region,omitempty"`
	Region *string `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty" form:"region" bson:"region,omitempty"`
	// Filter by content status (e.g. active, archived)
	// @gotags: `form:"status" json:"status,omitempty" bson:"status,omitempty"`
	Status *string `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status" bson:"status,omitempty"`
	// Filter by public visibility
	// @gotags: `form:"isPublic" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic *bool `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" form:"isPublic" bson:"isPublic,omitempty"`
	// Filter by tag
	// @gotags: `form:"tag" json:"tag,omitempty" bson:"tag,omitempty"`
	Tag *string `protobuf:"bytes,8,opt,name=tag,proto3,oneof" json:"tag,omitempty" form:"tag" bson:"tag,omitempty"`
	// Filter by uploader user ID
	// @gotags: `form:"uploaderId" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId *string `protobuf:"bytes,9,opt,name=uploader_id,json=uploaderId,proto3,oneof" json:"uploaderId,omitempty" form:"uploaderId" bson:"uploaderId,omitempty"`
	// Filter by site key (e.g. retrogames)
	// @gotags: `form:"site" json:"site,omitempty" bson:"site,omitempty"`
	Site *string `protobuf:"bytes,10,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site" bson:"site,omitempty"`
	// Filter by publication status
	// @gotags: `form:"isPublish" json:"isPublish,omitempty" bson:"isPublish,omitempty"`
	IsPublish *bool `protobuf:"varint,11,opt,name=is_publish,json=isPublish,proto3,oneof" json:"isPublish,omitempty" form:"isPublish" bson:"isPublish,omitempty"`
	// Filter by active status
	// @gotags: `form:"isActive" json:"isActive,omitempty" bson:"isActive,omitempty"`
	IsActive      *bool `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3,oneof" json:"isActive,omitempty" form:"isActive" bson:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomQuery) Reset() {
	*x = RomQuery{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomQuery) ProtoMessage() {}

func (x *RomQuery) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomQuery.ProtoReflect.Descriptor instead.
func (*RomQuery) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{4}
}

func (x *RomQuery) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomQuery) GetConsoleId() string {
	if x != nil && x.ConsoleId != nil {
		return *x.ConsoleId
	}
	return ""
}

func (x *RomQuery) GetConsoleKey() string {
	if x != nil && x.ConsoleKey != nil {
		return *x.ConsoleKey
	}
	return ""
}

func (x *RomQuery) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *RomQuery) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *RomQuery) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *RomQuery) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *RomQuery) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *RomQuery) GetUploaderId() string {
	if x != nil && x.UploaderId != nil {
		return *x.UploaderId
	}
	return ""
}

func (x *RomQuery) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomQuery) GetIsPublish() bool {
	if x != nil && x.IsPublish != nil {
		return *x.IsPublish
	}
	return false
}

func (x *RomQuery) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type RomSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of items to return (default 20, max 100)
	// @gotags: `form:"limit" json:"limit,omitempty" bson:"limit,omitempty"`
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty" form:"limit" bson:"limit,omitempty"`
	// Number of items to skip for pagination (default 0)
	// @gotags: `form:"offset" json:"offset,omitempty" bson:"offset,omitempty"`
	Offset *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty" form:"offset" bson:"offset,omitempty"`
	// Keyword search across title, description, and tags
	// @gotags: `form:"keyword" json:"keyword,omitempty" bson:"keyword,omitempty"`
	Keyword *string `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty" form:"keyword" bson:"keyword,omitempty"`
	// Field name to sort by (e.g. title, createdAt, releaseYear)
	// @gotags: `form:"sortby" json:"sortby,omitempty" bson:"sortby,omitempty"`
	Sortby *string `protobuf:"bytes,4,opt,name=sortby,proto3,oneof" json:"sortby,omitempty" form:"sortby" bson:"sortby,omitempty"`
	// Sort direction order (asc or desc, default desc)
	// @gotags: `form:"sortOrder" json:"sortOrder,omitempty" bson:"sortOrder,omitempty"`
	SortOrder *string `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sortOrder,omitempty" form:"sortOrder" bson:"sortOrder,omitempty"`
	// Nested query filters for ROM properties
	// @gotags: `json:"query,omitempty" bson:"query,omitempty"`
	Query *RomQuery `protobuf:"bytes,6,opt,name=query,proto3,oneof" json:"query,omitempty" bson:"query,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty" bson:"site,omitempty"`
	Site          *string `protobuf:"bytes,7,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site" bson:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomSearchRequest) Reset() {
	*x = RomSearchRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomSearchRequest) ProtoMessage() {}

func (x *RomSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomSearchRequest.ProtoReflect.Descriptor instead.
func (*RomSearchRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{5}
}

func (x *RomSearchRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *RomSearchRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *RomSearchRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *RomSearchRequest) GetSortby() string {
	if x != nil && x.Sortby != nil {
		return *x.Sortby
	}
	return ""
}

func (x *RomSearchRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

func (x *RomSearchRequest) GetQuery() *RomQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RomSearchRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type RomSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of ROM metadata items for the current page
	Roms []*RomMetadata `protobuf:"bytes,1,rep,name=roms,proto3" json:"roms,omitempty"`
	// Total count of items matching the query
	// @gotags: `json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	TotalCount int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	// Page size limit applied
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset applied
	Offset int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Calculated total number of pages
	// @gotags: `json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	TotalPages    int32 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomSearchResponse) Reset() {
	*x = RomSearchResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomSearchResponse) ProtoMessage() {}

func (x *RomSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomSearchResponse.ProtoReflect.Descriptor instead.
func (*RomSearchResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{6}
}

func (x *RomSearchResponse) GetRoms() []*RomMetadata {
	if x != nil {
		return x.Roms
	}
	return nil
}

func (x *RomSearchResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RomSearchResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RomSearchResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RomSearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MIME type
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	// File size in bytes
	// @gotags: `json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	SizeBytes int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	// ROM title
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// ROM description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Console system database ID or key
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	ConsoleId string `protobuf:"bytes,6,opt,name=console_id,json=consoleId,proto3" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	// URL-friendly permalink
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty"`
	Permalink string `protobuf:"bytes,7,opt,name=permalink,proto3" json:"permalink,omitempty" bson:"permalink,omitempty"`
	// Game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty"`
	Publisher string `protobuf:"bytes,8,opt,name=publisher,proto3" json:"publisher,omitempty" bson:"publisher,omitempty"`
	// Release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32 `protobuf:"varint,9,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	// Game genre
	Genre string `protobuf:"bytes,10,opt,name=genre,proto3" json:"genre,omitempty"`
	// Release region
	Region string `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	// Supported players
	Players int32 `protobuf:"varint,12,opt,name=players,proto3" json:"players,omitempty"`
	// Content rating
	Rating string `protobuf:"bytes,13,opt,name=rating,proto3" json:"rating,omitempty"`
	// Category tags
	Tags []string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,15,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Custom storage key if specified
	// @gotags: `json:"customKey,omitempty" bson:"customKey,omitempty"`
	CustomKey string `protobuf:"bytes,16,opt,name=custom_key,json=customKey,proto3" json:"customKey,omitempty" bson:"customKey,omitempty"`
	// Uploader user ID
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,17,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// Uploader username
	// @gotags: `json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	UploaderUsername string `protobuf:"bytes,18,opt,name=uploader_username,json=uploaderUsername,proto3" json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,19,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Array of image groups categorized by aspect ratio
	// @gotags: `json:"images,omitempty" bson:"images,omitempty"`
	Images []*image.AspectRatioImages `protobuf:"bytes,20,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty"`
	// Publication status flag
	// @gotags: `json:"isPublish,omitempty" bson:"isPublish,omitempty"`
	IsPublish bool `protobuf:"varint,21,opt,name=is_publish,json=isPublish,proto3" json:"isPublish,omitempty" bson:"isPublish,omitempty"`
	// Active status flag
	// @gotags: `json:"isActive,omitempty" bson:"isActive,omitempty"`
	IsActive      bool `protobuf:"varint,22,opt,name=is_active,json=isActive,proto3" json:"isActive,omitempty" bson:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FileInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FileInfo) GetConsoleId() string {
	if x != nil {
		return x.ConsoleId
	}
	return ""
}

func (x *FileInfo) GetPermalink() string {
	if x != nil {
		return x.Permalink
	}
	return ""
}

func (x *FileInfo) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *FileInfo) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *FileInfo) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *FileInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *FileInfo) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *FileInfo) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *FileInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FileInfo) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *FileInfo) GetCustomKey() string {
	if x != nil {
		return x.CustomKey
	}
	return ""
}

func (x *FileInfo) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *FileInfo) GetUploaderUsername() string {
	if x != nil {
		return x.UploaderUsername
	}
	return ""
}

func (x *FileInfo) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *FileInfo) GetImages() []*image.AspectRatioImages {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *FileInfo) GetIsPublish() bool {
	if x != nil {
		return x.IsPublish
	}
	return false
}

func (x *FileInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UploadRomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM display title
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// ROM description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Console system database ID
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty" form:"consoleId"`
	ConsoleId string `protobuf:"bytes,3,opt,name=console_id,json=consoleId,proto3" json:"consoleId,omitempty" bson:"consoleId,omitempty" form:"consoleId"`
	// Console system key fallback (e.g. gba, snes)
	// @gotags: `json:"console,omitempty" bson:"console,omitempty" form:"console"`
	Console string `protobuf:"bytes,4,opt,name=console,proto3" json:"console,omitempty" bson:"console,omitempty" form:"console"`
	// URL-friendly permalink (e.g. /super-mario)
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty" form:"permalink"`
	Permalink string `protobuf:"bytes,5,opt,name=permalink,proto3" json:"permalink,omitempty" bson:"permalink,omitempty" form:"permalink"`
	// Game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty" form:"publisher"`
	Publisher string `protobuf:"bytes,6,opt,name=publisher,proto3" json:"publisher,omitempty" bson:"publisher,omitempty" form:"publisher"`
	// Release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty" form:"releaseYear"`
	ReleaseYear int32 `protobuf:"varint,7,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty" form:"releaseYear"`
	// Game genre
	Genre string `protobuf:"bytes,8,opt,name=genre,proto3" json:"genre,omitempty"`
	// Release region
	Region string `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	// Supported players
	Players int32 `protobuf:"varint,10,opt,name=players,proto3" json:"players,omitempty"`
	// Content rating
	Rating string `protobuf:"bytes,11,opt,name=rating,proto3" json:"rating,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty" form:"isPublic"`
	IsPublic *bool `protobuf:"varint,12,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" bson:"isPublic,omitempty" form:"isPublic"`
	// Category tags
	Tags []string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	// Custom storage key
	// @gotags: `json:"customKey,omitempty" bson:"customKey,omitempty" form:"customKey"`
	CustomKey string `protobuf:"bytes,14,opt,name=custom_key,json=customKey,proto3" json:"customKey,omitempty" bson:"customKey,omitempty" form:"customKey"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty" form:"site"`
	Site *string `protobuf:"bytes,15,opt,name=site,proto3,oneof" json:"site,omitempty" bson:"site,omitempty" form:"site"`
	// Array of image groups categorized by aspect ratio
	// @gotags: `json:"images,omitempty" bson:"images,omitempty" form:"images"`
	Images []*image.AspectRatioImages `protobuf:"bytes,16,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty" form:"images"`
	// Publication status flag
	// @gotags: `json:"isPublish,omitempty" bson:"isPublish,omitempty" form:"isPublish"`
	IsPublish *bool `protobuf:"varint,17,opt,name=is_publish,json=isPublish,proto3,oneof" json:"isPublish,omitempty" bson:"isPublish,omitempty" form:"isPublish"`
	// Active status flag
	// @gotags: `json:"isActive,omitempty" bson:"isActive,omitempty" form:"isActive"`
	IsActive      *bool `protobuf:"varint,18,opt,name=is_active,json=isActive,proto3,oneof" json:"isActive,omitempty" bson:"isActive,omitempty" form:"isActive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRomRequest) Reset() {
	*x = UploadRomRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRomRequest) ProtoMessage() {}

func (x *UploadRomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRomRequest.ProtoReflect.Descriptor instead.
func (*UploadRomRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{8}
}

func (x *UploadRomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadRomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadRomRequest) GetConsoleId() string {
	if x != nil {
		return x.ConsoleId
	}
	return ""
}

func (x *UploadRomRequest) GetConsole() string {
	if x != nil {
		return x.Console
	}
	return ""
}

func (x *UploadRomRequest) GetPermalink() string {
	if x != nil {
		return x.Permalink
	}
	return ""
}

func (x *UploadRomRequest) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *UploadRomRequest) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *UploadRomRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *UploadRomRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UploadRomRequest) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *UploadRomRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *UploadRomRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *UploadRomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UploadRomRequest) GetCustomKey() string {
	if x != nil {
		return x.CustomKey
	}
	return ""
}

func (x *UploadRomRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *UploadRomRequest) GetImages() []*image.AspectRatioImages {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UploadRomRequest) GetIsPublish() bool {
	if x != nil && x.IsPublish != nil {
		return *x.IsPublish
	}
	return false
}

func (x *UploadRomRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type RomUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestData:
	//
	//	*RomUploadRequest_FileInfo
	//	*RomUploadRequest_ChunkData
	RequestData   isRomUploadRequest_RequestData `protobuf_oneof:"request_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUploadRequest) Reset() {
	*x = RomUploadRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadRequest) ProtoMessage() {}

func (x *RomUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadRequest.ProtoReflect.Descriptor instead.
func (*RomUploadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{9}
}

func (x *RomUploadRequest) GetRequestData() isRomUploadRequest_RequestData {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *RomUploadRequest) GetFileInfo() *FileInfo {
	if x != nil {
		if x, ok := x.RequestData.(*RomUploadRequest_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *RomUploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.RequestData.(*RomUploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isRomUploadRequest_RequestData interface {
	isRomUploadRequest_RequestData()
}

type RomUploadRequest_FileInfo struct {
	// ROM metadata for initial chunk
	// @gotags: `json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof" json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
}

type RomUploadRequest_ChunkData struct {
	// Binary chunk data
	// @gotags: `json:"chunkData,omitempty" bson:"chunkData,omitempty"`
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof" json:"chunkData,omitempty" bson:"chunkData,omitempty"`
}

func (*RomUploadRequest_FileInfo) isRomUploadRequest_RequestData() {}

func (*RomUploadRequest_ChunkData) isRomUploadRequest_RequestData() {}

type RomUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uploaded ROM metadata
	Rom           *RomMetadata `protobuf:"bytes,1,opt,name=rom,proto3" json:"rom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUploadResponse) Reset() {
	*x = RomUploadResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadResponse) ProtoMessage() {}

func (x *RomUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadResponse.ProtoReflect.Descriptor instead.
func (*RomUploadResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{10}
}

func (x *RomUploadResponse) GetRom() *RomMetadata {
	if x != nil {
		return x.Rom
	}
	return nil
}

type RomUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ROM identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Updated ROM title
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Updated ROM description
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Updated console ID
	// @gotags: `json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	ConsoleId *string `protobuf:"bytes,4,opt,name=console_id,json=consoleId,proto3,oneof" json:"consoleId,omitempty" bson:"consoleId,omitempty"`
	// Updated permalink
	// @gotags: `json:"permalink,omitempty" bson:"permalink,omitempty"`
	Permalink *string `protobuf:"bytes,5,opt,name=permalink,proto3,oneof" json:"permalink,omitempty" bson:"permalink,omitempty"`
	// Updated game publisher
	// @gotags: `json:"publisher,omitempty" bson:"publisher,omitempty"`
	Publisher *string `protobuf:"bytes,6,opt,name=publisher,proto3,oneof" json:"publisher,omitempty" bson:"publisher,omitempty"`
	// Updated release year
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear *int32 `protobuf:"varint,7,opt,name=release_year,json=releaseYear,proto3,oneof" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	// Updated genre
	Genre *string `protobuf:"bytes,8,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	// Updated region
	Region *string `protobuf:"bytes,9,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// Updated player count
	Players *int32 `protobuf:"varint,10,opt,name=players,proto3,oneof" json:"players,omitempty"`
	// Updated content rating
	Rating *string `protobuf:"bytes,11,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	// Updated tags
	Tags []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// Updated public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic *bool `protobuf:"varint,13,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Updated lifecycle status
	// @gotags: `json:"status,omitempty" bson:"status,omitempty"`
	Status *string `protobuf:"bytes,14,opt,name=status,proto3,oneof" json:"status,omitempty" bson:"status,omitempty"`
	// Updated site identifier
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site *string `protobuf:"bytes,15,opt,name=site,proto3,oneof" json:"site,omitempty" bson:"site,omitempty"`
	// Updated array of image groups categorized by aspect ratio
	// @gotags: `json:"images,omitempty" bson:"images,omitempty"`
	Images []*image.AspectRatioImages `protobuf:"bytes,16,rep,name=images,proto3" json:"images,omitempty" bson:"images,omitempty"`
	// Updated publication status flag
	// @gotags: `json:"isPublish,omitempty" bson:"isPublish,omitempty"`
	IsPublish *bool `protobuf:"varint,17,opt,name=is_publish,json=isPublish,proto3,oneof" json:"isPublish,omitempty" bson:"isPublish,omitempty"`
	// Updated active status flag
	// @gotags: `json:"isActive,omitempty" bson:"isActive,omitempty"`
	IsActive      *bool `protobuf:"varint,18,opt,name=is_active,json=isActive,proto3,oneof" json:"isActive,omitempty" bson:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUpdateRequest) Reset() {
	*x = RomUpdateRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUpdateRequest) ProtoMessage() {}

func (x *RomUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUpdateRequest.ProtoReflect.Descriptor instead.
func (*RomUpdateRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{11}
}

func (x *RomUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomUpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *RomUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RomUpdateRequest) GetConsoleId() string {
	if x != nil && x.ConsoleId != nil {
		return *x.ConsoleId
	}
	return ""
}

func (x *RomUpdateRequest) GetPermalink() string {
	if x != nil && x.Permalink != nil {
		return *x.Permalink
	}
	return ""
}

func (x *RomUpdateRequest) GetPublisher() string {
	if x != nil && x.Publisher != nil {
		return *x.Publisher
	}
	return ""
}

func (x *RomUpdateRequest) GetReleaseYear() int32 {
	if x != nil && x.ReleaseYear != nil {
		return *x.ReleaseYear
	}
	return 0
}

func (x *RomUpdateRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *RomUpdateRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *RomUpdateRequest) GetPlayers() int32 {
	if x != nil && x.Players != nil {
		return *x.Players
	}
	return 0
}

func (x *RomUpdateRequest) GetRating() string {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return ""
}

func (x *RomUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RomUpdateRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *RomUpdateRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *RomUpdateRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *RomUpdateRequest) GetImages() []*image.AspectRatioImages {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *RomUpdateRequest) GetIsPublish() bool {
	if x != nil && x.IsPublish != nil {
		return *x.IsPublish
	}
	return false
}

func (x *RomUpdateRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type RomDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ROM identifier to delete
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Hard delete flag (permanently remove file from storage and database)
	// @gotags: `json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	HardDelete bool `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,3,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDeleteRequest) Reset() {
	*x = RomDeleteRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDeleteRequest) ProtoMessage() {}

func (x *RomDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDeleteRequest.ProtoReflect.Descriptor instead.
func (*RomDeleteRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{12}
}

func (x *RomDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomDeleteRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

func (x *RomDeleteRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type RomDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDeleteResponse) Reset() {
	*x = RomDeleteResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDeleteResponse) ProtoMessage() {}

func (x *RomDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDeleteResponse.ProtoReflect.Descriptor instead.
func (*RomDeleteResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{13}
}

func (x *RomDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RomDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RomShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ROM identifier to share
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pre-signed download URL expiration duration in seconds
	// @gotags: `json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	ExpiresInSec int32 `protobuf:"varint,2,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,3,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomShareRequest) Reset() {
	*x = RomShareRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomShareRequest) ProtoMessage() {}

func (x *RomShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomShareRequest.ProtoReflect.Descriptor instead.
func (*RomShareRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{14}
}

func (x *RomShareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomShareRequest) GetExpiresInSec() int32 {
	if x != nil {
		return x.ExpiresInSec
	}
	return 0
}

func (x *RomShareRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type RomShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ROM identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Generated pre-signed download URL
	// @gotags: `json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	// ISO-8601 expiration timestamp
	// @gotags: `json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomShareResponse) Reset() {
	*x = RomShareResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomShareResponse) ProtoMessage() {}

func (x *RomShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomShareResponse.ProtoReflect.Descriptor instead.
func (*RomShareResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{15}
}

func (x *RomShareResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomShareResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *RomShareResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ListConsolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional site identifier filter
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,1,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolesRequest) Reset() {
	*x = ListConsolesRequest{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolesRequest) ProtoMessage() {}

func (x *ListConsolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolesRequest.ProtoReflect.Descriptor instead.
func (*ListConsolesRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{16}
}

func (x *ListConsolesRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ListConsolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of supported console systems
	Consoles      []*ConsoleInfo `protobuf:"bytes,1,rep,name=consoles,proto3" json:"consoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolesResponse) Reset() {
	*x = ListConsolesResponse{}
	mi := &file_content_v1_rom_rom_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolesResponse) ProtoMessage() {}

func (x *ListConsolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_rom_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolesResponse.ProtoReflect.Descriptor instead.
func (*ListConsolesResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_rom_proto_rawDescGZIP(), []int{17}
}

func (x *ListConsolesResponse) GetConsoles() []*ConsoleInfo {
	if x != nil {
		return x.Consoles
	}
	return nil
}

var File_content_v1_rom_rom_proto protoreflect.FileDescriptor

const file_content_v1_rom_rom_proto_rawDesc = "" +
	"\n" +
	"\x18content/v1/rom/rom.proto\x12\x0econtent.v1.rom\x1a\x16common/v1/common.proto\x1a\x1ccontent/v1/image/image.proto\"\xe0\x02\n" +
	"\vConsoleInfo\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x03(\tR\n" +
	"extensions\x12\"\n" +
	"\fmanufacturer\x18\b \x01(\tR\fmanufacturer\x12!\n" +
	"\frelease_year\x18\t \x01(\x05R\vreleaseYear\x12\x19\n" +
	"\bicon_url\x18\n" +
	" \x01(\tR\aiconUrl\x12#\n" +
	"\rcontent_count\x18\v \x01(\x03R\fcontentCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\xcf\x06\n" +
	"\vRomMetadata\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tpermalink\x18\x05 \x01(\tR\tpermalink\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"console_id\x18\a \x01(\tR\tconsoleId\x12\x17\n" +
	"\afile_id\x18\b \x01(\tR\x06fileId\x12\x1c\n" +
	"\tpublisher\x18\n" +
	" \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\v \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\f \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\r \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\x0e \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\x0f \x01(\tR\x06rating\x12\x12\n" +
	"\x04tags\x18\x10 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x11 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12\x1f\n" +
	"\vuploader_id\x18\x13 \x01(\tR\n" +
	"uploaderId\x12+\n" +
	"\x11uploader_username\x18\x14 \x01(\tR\x10uploaderUsername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x15 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\tR\tupdatedAt\x12F\n" +
	"\x10console_metadata\x18\x17 \x01(\v2\x1b.content.v1.rom.ConsoleInfoR\x0fconsoleMetadata\x12<\n" +
	"\rfile_metadata\x18\x18 \x01(\v2\x17.common.v1.FileMetadataR\ffileMetadata\x12;\n" +
	"\x06images\x18\x19 \x03(\v2#.content.v1.image.AspectRatioImagesR\x06images\x12\x1d\n" +
	"\n" +
	"is_publish\x18\x1a \x01(\bR\tisPublish\x12\x1b\n" +
	"\tis_active\x18\x1b \x01(\bR\bisActive\"\xa0\x01\n" +
	"\rRomGetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x04 \x01(\tH\x02R\x04site\x88\x01\x01\x12!\n" +
	"\tpermalink\x18\x05 \x01(\tH\x03R\tpermalink\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_siteB\f\n" +
	"\n" +
	"_permalink\"\xa5\x01\n" +
	"\x12RomDownloadRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x04 \x01(\tH\x02R\x04site\x88\x01\x01\x12!\n" +
	"\tpermalink\x18\x05 \x01(\tH\x03R\tpermalink\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_siteB\f\n" +
	"\n" +
	"_permalink\"\x94\x04\n" +
	"\bRomQuery\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"console_id\x18\x02 \x01(\tH\x01R\tconsoleId\x88\x01\x01\x12$\n" +
	"\vconsole_key\x18\x03 \x01(\tH\x02R\n" +
	"consoleKey\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\x04 \x01(\tH\x03R\x05genre\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x04R\x06region\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x05R\x06status\x88\x01\x01\x12 \n" +
	"\tis_public\x18\a \x01(\bH\x06R\bisPublic\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\b \x01(\tH\aR\x03tag\x88\x01\x01\x12$\n" +
	"\vuploader_id\x18\t \x01(\tH\bR\n" +
	"uploaderId\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\n" +
	" \x01(\tH\tR\x04site\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_publish\x18\v \x01(\bH\n" +
	"R\tisPublish\x88\x01\x01\x12 \n" +
	"\tis_active\x18\f \x01(\bH\vR\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_console_idB\x0e\n" +
	"\f_console_keyB\b\n" +
	"\x06_genreB\t\n" +
	"\a_regionB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_is_publicB\x06\n" +
	"\x04_tagB\x0e\n" +
	"\f_uploader_idB\a\n" +
	"\x05_siteB\r\n" +
	"\v_is_publishB\f\n" +
	"\n" +
	"_is_active\"\xc6\x02\n" +
	"\x10RomSearchRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01\x12\x1b\n" +
	"\x06sortby\x18\x04 \x01(\tH\x03R\x06sortby\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tH\x04R\tsortOrder\x88\x01\x01\x123\n" +
	"\x05query\x18\x06 \x01(\v2\x18.content.v1.rom.RomQueryH\x05R\x05query\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\a \x01(\tH\x06R\x04site\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\n" +
	"\n" +
	"\b_keywordB\t\n" +
	"\a_sortbyB\r\n" +
	"\v_sort_orderB\b\n" +
	"\x06_queryB\a\n" +
	"\x05_site\"\xb4\x01\n" +
	"\x11RomSearchResponse\x12/\n" +
	"\x04roms\x18\x01 \x03(\v2\x1b.content.v1.rom.RomMetadataR\x04roms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x9b\x05\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"console_id\x18\x06 \x01(\tR\tconsoleId\x12\x1c\n" +
	"\tpermalink\x18\a \x01(\tR\tpermalink\x12\x1c\n" +
	"\tpublisher\x18\b \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\t \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\n" +
	" \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\v \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\f \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\r \x01(\tR\x06rating\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x0f \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"custom_key\x18\x10 \x01(\tR\tcustomKey\x12\x1f\n" +
	"\vuploader_id\x18\x11 \x01(\tR\n" +
	"uploaderId\x12+\n" +
	"\x11uploader_username\x18\x12 \x01(\tR\x10uploaderUsername\x12\x12\n" +
	"\x04site\x18\x13 \x01(\tR\x04site\x12;\n" +
	"\x06images\x18\x14 \x03(\v2#.content.v1.image.AspectRatioImagesR\x06images\x12\x1d\n" +
	"\n" +
	"is_publish\x18\x15 \x01(\bR\tisPublish\x12\x1b\n" +
	"\tis_active\x18\x16 \x01(\bR\bisActive\"\xe7\x04\n" +
	"\x10UploadRomRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"console_id\x18\x03 \x01(\tR\tconsoleId\x12\x18\n" +
	"\aconsole\x18\x04 \x01(\tR\aconsole\x12\x1c\n" +
	"\tpermalink\x18\x05 \x01(\tR\tpermalink\x12\x1c\n" +
	"\tpublisher\x18\x06 \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\a \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\b \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\n" +
	" \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\v \x01(\tR\x06rating\x12 \n" +
	"\tis_public\x18\f \x01(\bH\x00R\bisPublic\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"custom_key\x18\x0e \x01(\tR\tcustomKey\x12\x17\n" +
	"\x04site\x18\x0f \x01(\tH\x01R\x04site\x88\x01\x01\x12;\n" +
	"\x06images\x18\x10 \x03(\v2#.content.v1.image.AspectRatioImagesR\x06images\x12\"\n" +
	"\n" +
	"is_publish\x18\x11 \x01(\bH\x02R\tisPublish\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x12 \x01(\bH\x03R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_publicB\a\n" +
	"\x05_siteB\r\n" +
	"\v_is_publishB\f\n" +
	"\n" +
	"_is_active\"|\n" +
	"\x10RomUploadRequest\x127\n" +
	"\tfile_info\x18\x01 \x01(\v2\x18.content.v1.rom.FileInfoH\x00R\bfileInfo\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x0e\n" +
	"\frequest_data\"B\n" +
	"\x11RomUploadResponse\x12-\n" +
	"\x03rom\x18\x01 \x01(\v2\x1b.content.v1.rom.RomMetadataR\x03rom\"\x9a\x06\n" +
	"\x10RomUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"console_id\x18\x04 \x01(\tH\x02R\tconsoleId\x88\x01\x01\x12!\n" +
	"\tpermalink\x18\x05 \x01(\tH\x03R\tpermalink\x88\x01\x01\x12!\n" +
	"\tpublisher\x18\x06 \x01(\tH\x04R\tpublisher\x88\x01\x01\x12&\n" +
	"\frelease_year\x18\a \x01(\x05H\x05R\vreleaseYear\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\b \x01(\tH\x06R\x05genre\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\t \x01(\tH\aR\x06region\x88\x01\x01\x12\x1d\n" +
	"\aplayers\x18\n" +
	" \x01(\x05H\bR\aplayers\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\v \x01(\tH\tR\x06rating\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12 \n" +
	"\tis_public\x18\r \x01(\bH\n" +
	"R\bisPublic\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x0e \x01(\tH\vR\x06status\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x0f \x01(\tH\fR\x04site\x88\x01\x01\x12;\n" +
	"\x06images\x18\x10 \x03(\v2#.content.v1.image.AspectRatioImagesR\x06images\x12\"\n" +
	"\n" +
	"is_publish\x18\x11 \x01(\bH\rR\tisPublish\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x12 \x01(\bH\x0eR\bisActive\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_console_idB\f\n" +
	"\n" +
	"_permalinkB\f\n" +
	"\n" +
	"_publisherB\x0f\n" +
	"\r_release_yearB\b\n" +
	"\x06_genreB\t\n" +
	"\a_regionB\n" +
	"\n" +
	"\b_playersB\t\n" +
	"\a_ratingB\f\n" +
	"\n" +
	"_is_publicB\t\n" +
	"\a_statusB\a\n" +
	"\x05_siteB\r\n" +
	"\v_is_publishB\f\n" +
	"\n" +
	"_is_active\"e\n" +
	"\x10RomDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\x12\x17\n" +
	"\x04site\x18\x03 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"G\n" +
	"\x11RomDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\x0fRomShareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eexpires_in_sec\x18\x02 \x01(\x05R\fexpiresInSec\x12\x17\n" +
	"\x04site\x18\x03 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"d\n" +
	"\x10RomShareResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"7\n" +
	"\x13ListConsolesRequest\x12\x17\n" +
	"\x04site\x18\x01 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"O\n" +
	"\x14ListConsolesResponse\x127\n" +
	"\bconsoles\x18\x01 \x03(\v2\x1b.content.v1.rom.ConsoleInfoR\bconsolesB4Z2github.com/AyuuSaxena/protos-go/content/v1/rom;romb\x06proto3"

var (
	file_content_v1_rom_rom_proto_rawDescOnce sync.Once
	file_content_v1_rom_rom_proto_rawDescData []byte
)

func file_content_v1_rom_rom_proto_rawDescGZIP() []byte {
	file_content_v1_rom_rom_proto_rawDescOnce.Do(func() {
		file_content_v1_rom_rom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_rom_rom_proto_rawDesc), len(file_content_v1_rom_rom_proto_rawDesc)))
	})
	return file_content_v1_rom_rom_proto_rawDescData
}

var file_content_v1_rom_rom_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_content_v1_rom_rom_proto_goTypes = []any{
	(*ConsoleInfo)(nil),             // 0: content.v1.rom.ConsoleInfo
	(*RomMetadata)(nil),             // 1: content.v1.rom.RomMetadata
	(*RomGetRequest)(nil),           // 2: content.v1.rom.RomGetRequest
	(*RomDownloadRequest)(nil),      // 3: content.v1.rom.RomDownloadRequest
	(*RomQuery)(nil),                // 4: content.v1.rom.RomQuery
	(*RomSearchRequest)(nil),        // 5: content.v1.rom.RomSearchRequest
	(*RomSearchResponse)(nil),       // 6: content.v1.rom.RomSearchResponse
	(*FileInfo)(nil),                // 7: content.v1.rom.FileInfo
	(*UploadRomRequest)(nil),        // 8: content.v1.rom.UploadRomRequest
	(*RomUploadRequest)(nil),        // 9: content.v1.rom.RomUploadRequest
	(*RomUploadResponse)(nil),       // 10: content.v1.rom.RomUploadResponse
	(*RomUpdateRequest)(nil),        // 11: content.v1.rom.RomUpdateRequest
	(*RomDeleteRequest)(nil),        // 12: content.v1.rom.RomDeleteRequest
	(*RomDeleteResponse)(nil),       // 13: content.v1.rom.RomDeleteResponse
	(*RomShareRequest)(nil),         // 14: content.v1.rom.RomShareRequest
	(*RomShareResponse)(nil),        // 15: content.v1.rom.RomShareResponse
	(*ListConsolesRequest)(nil),     // 16: content.v1.rom.ListConsolesRequest
	(*ListConsolesResponse)(nil),    // 17: content.v1.rom.ListConsolesResponse
	(*v1.FileMetadata)(nil),         // 18: common.v1.FileMetadata
	(*image.AspectRatioImages)(nil), // 19: content.v1.image.AspectRatioImages
}
var file_content_v1_rom_rom_proto_depIdxs = []int32{
	0,  // 0: content.v1.rom.RomMetadata.console_metadata:type_name -> content.v1.rom.ConsoleInfo
	18, // 1: content.v1.rom.RomMetadata.file_metadata:type_name -> common.v1.FileMetadata
	19, // 2: content.v1.rom.RomMetadata.images:type_name -> content.v1.image.AspectRatioImages
	4,  // 3: content.v1.rom.RomSearchRequest.query:type_name -> content.v1.rom.RomQuery
	1,  // 4: content.v1.rom.RomSearchResponse.roms:type_name -> content.v1.rom.RomMetadata
	19, // 5: content.v1.rom.FileInfo.images:type_name -> content.v1.image.AspectRatioImages
	19, // 6: content.v1.rom.UploadRomRequest.images:type_name -> content.v1.image.AspectRatioImages
	7,  // 7: content.v1.rom.RomUploadRequest.file_info:type_name -> content.v1.rom.FileInfo
	1,  // 8: content.v1.rom.RomUploadResponse.rom:type_name -> content.v1.rom.RomMetadata
	19, // 9: content.v1.rom.RomUpdateRequest.images:type_name -> content.v1.image.AspectRatioImages
	0,  // 10: content.v1.rom.ListConsolesResponse.consoles:type_name -> content.v1.rom.ConsoleInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_content_v1_rom_rom_proto_init() }
func file_content_v1_rom_rom_proto_init() {
	if File_content_v1_rom_rom_proto != nil {
		return
	}
	file_content_v1_rom_rom_proto_msgTypes[2].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[3].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[4].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[5].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[8].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[9].OneofWrappers = []any{
		(*RomUploadRequest_FileInfo)(nil),
		(*RomUploadRequest_ChunkData)(nil),
	}
	file_content_v1_rom_rom_proto_msgTypes[11].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[12].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[14].OneofWrappers = []any{}
	file_content_v1_rom_rom_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_rom_rom_proto_rawDesc), len(file_content_v1_rom_rom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_v1_rom_rom_proto_goTypes,
		DependencyIndexes: file_content_v1_rom_rom_proto_depIdxs,
		MessageInfos:      file_content_v1_rom_rom_proto_msgTypes,
	}.Build()
	File_content_v1_rom_rom_proto = out.File
	file_content_v1_rom_rom_proto_goTypes = nil
	file_content_v1_rom_rom_proto_depIdxs = nil
}
