// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: management/v1/image/image.proto

package image

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImageGetRequest is the request to retrieve metadata for a single image by ID.
type ImageGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique image identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional site/tenant identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,2,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageGetRequest) Reset() {
	*x = ImageGetRequest{}
	mi := &file_management_v1_image_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGetRequest) ProtoMessage() {}

func (x *ImageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_image_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGetRequest.ProtoReflect.Descriptor instead.
func (*ImageGetRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_image_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageGetRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

var File_management_v1_image_image_proto protoreflect.FileDescriptor

const file_management_v1_image_image_proto_rawDesc = "" +
	"\n" +
	"\x1fmanagement/v1/image/image.proto\x12\x13management.v1.image\"C\n" +
	"\x0fImageGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04site\x18\x02 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_siteB;Z9github.com/AyuuSaxena/protos-go/management/v1/image;imageb\x06proto3"

var (
	file_management_v1_image_image_proto_rawDescOnce sync.Once
	file_management_v1_image_image_proto_rawDescData []byte
)

func file_management_v1_image_image_proto_rawDescGZIP() []byte {
	file_management_v1_image_image_proto_rawDescOnce.Do(func() {
		file_management_v1_image_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_v1_image_image_proto_rawDesc), len(file_management_v1_image_image_proto_rawDesc)))
	})
	return file_management_v1_image_image_proto_rawDescData
}

var file_management_v1_image_image_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_management_v1_image_image_proto_goTypes = []any{
	(*ImageGetRequest)(nil), // 0: management.v1.image.ImageGetRequest
}
var file_management_v1_image_image_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_management_v1_image_image_proto_init() }
func file_management_v1_image_image_proto_init() {
	if File_management_v1_image_image_proto != nil {
		return
	}
	file_management_v1_image_image_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_v1_image_image_proto_rawDesc), len(file_management_v1_image_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_v1_image_image_proto_goTypes,
		DependencyIndexes: file_management_v1_image_image_proto_depIdxs,
		MessageInfos:      file_management_v1_image_image_proto_msgTypes,
	}.Build()
	File_management_v1_image_image_proto = out.File
	file_management_v1_image_image_proto_goTypes = nil
	file_management_v1_image_image_proto_depIdxs = nil
}
